plugins {
    alias libs.plugins.android.app
    alias libs.plugins.kotlin.android
}

android {
    namespace **APKAPPID**
    compileSdkVersion = 34
    
    defaultConfig {
        applicationId = **APKAPPID**
        minSdkVersion 21
        targetSdkVersion System.getenv("NDK_PLATFORM_TARGET")
        externalNativeBuild.cmake {
            arguments '-DANDROID_STL=c++_shared'
        }
        ndk.abiFilters 'arm64-v8a'
    }
    buildTypes.release {
        minifyEnabled false
        proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
    }
    sourceSets.main {
        java.srcDirs = ["src/main"]
        jniLibs.srcDir System.getenv("NDK_HOME") + '/sources/third_party/vulkan/src/build-android/jniLibs'
        assets.srcDir '../../assets'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation libs.androidx.appcompat
    implementation libs.androidx.lifecycle.viewmodel
}
