[package]
name = "peridot-semantic-shader"
version = "0.1.0"
edition = "2021"

[features]
default = ["with-loader-impl", "bedrock-implements"]
bedrock-implements = ["bedrock/Implements"]
with-loader-impl = ["dep:peridot", "bedrock-implements"]

[lints]
workspace = true

[dependencies]
bedrock.workspace = true
peridot-serialization-utils.path = "../serialization-utils"
thiserror = "2.0"
peridot = { path = "../../base", optional = true }
