[package]
name = "peridot-rendering-configuration"
version = "0.1.0"
edition = "2024"

[features]
default = []
with-loader-impl = ["dep:peridot"]
with-asset-processing = ["dep:peridot-asset-processing", "compilation"]
compilation = ["dep:slang", "dep:thiserror"]
debug-dumps = ["dep:spirv-tools"]

[dependencies]
peridot-serialization-utils = { path = "../serialization-utils" }
peridot = { path = "../../base", optional = true }
peridot-semantic-shader = { path = "../semantic-shader", default-features = false }
slang = { path = "../../thirdparty/slang", optional = true }
thiserror = { workspace = true, optional = true }
tracing = { workspace = true }
peridot-asset-processing = { path = "../asset-processing", optional = true }
futures-io = { workspace = true }
futures-util = { workspace = true, features = ["io"] }
peridot-native-io = { path = "../native-io" }
pinned-futures-helper.path = "../../base-lib/pinned-futures-helper"
spirv-tools = { path = "../../thirdparty/spirv-tools", optional = true }

[lints]
workspace = true
