#!/usr/bin/env bash

set -e

SCRIPT_PATH=$(dirname $0)
ENTRY_TY_NAME="Game"
CARGO_SUBCOMMAND="build"
NO_POSTLINK=0
AFTER_RUN=0
unset ASSET_PATH
FEATURES=( "bedrock/VK_MVK_macos_surface" )
UPDATE_DEPS=0
while [ $# -gt 0 ]; do
    case "$1" in
        "--EntryTyName" | "-e")
            ENTRY_TY_NAME=$2
            shift 2
            ;;
        "--Run" | "-r")
            AFTER_RUN=1
            NO_POSTLINK=0
            shift
            ;;
        "--RunTests")
            CARGO_SUBCOMMAND="test"
            NO_POSTLINK=1
            shift
            ;;
        "--RunChecks")
            CARGO_SUBCOMMAND="check"
            NO_POSTLINK=1
            shift
            ;;
        "-AssetDirectory" | "-a")
            ASSET_PATH=$(realpath $2)
            shift 2
            ;;
        "--Feature" | "-f")
            FEATURES+=" $2"
            shift 2
            ;;
        "--UpdateDeps" | "-u")
            UPDATE_DEPS=1
            shift
            ;;
        *)
            if [ -z ${USERLIB_DIRECTORY+x} ]; then USERLIB_DIRECTORY=$1; fi
            shift
            ;;
    esac
done
if [ -z ${USERLIB_DIRECTORY+x} ]; then echo "Error: User Game Project Directory required"; exit 1; fi

. $SCRIPT_PATH/../common.sh

PACKAGE_NAME=`find_package_names $USERLIB_DIRECTORY/Cargo.toml | head -n 1`
echo -e "🛠  Building Project \x1b[1;36m$PACKAGE_NAME\x1b[m for \x1b[33mmacOS\x1b[m Deployment..."

USERLIB_PATH=`realpath $USERLIB_DIRECTORY`
gen_manifest $PACKAGE_NAME $USERLIB_PATH $SCRIPT_PATH/Cargo.template.toml > $SCRIPT_PATH/Cargo.toml
echo -e "//! Auto Generated by build script\n\npub use ${PACKAGE_NAME//-/_}::$ENTRY_TY_NAME as Game;" > $SCRIPT_PATH/src/userlib.rs

if [ ! -z ${ASSET_PATH+x} ]; then
    echo "Packaging Assets..."
    $SCRIPT_PATH/../../target/release/peridot-archiver new $ASSET_PATH -o $SCRIPT_PATH/peridot-cradle/assets.par -b $ASSET_PATH/
fi

echo "Building GameCore..."
FEATURE_STRING=($(echo "${FEATURES[@]}" | tr ' ' '\n' | sort -u | tr '\n' ','))
echo $FEATURE_STRING
if [ $UPDATE_DEPS -ne 0 ]; then (cd $SCRIPT_PATH; cargo update); fi
(cd $SCRIPT_PATH; cargo $CARGO_SUBCOMMAND --features $FEATURE_STRING)

if [ $NO_POSTLINK -eq 0 ]; then
    echo "Building App Bundle..."
    [ ! -d $SCRIPT_PATH/peridot-cradle/rlibs ] && mkdir -p $SCRIPT_PATH/peridot-cradle/rlibs
    cp $SCRIPT_PATH/target/debug/libpegamelib.a $SCRIPT_PATH/peridot-cradle/rlibs/
    xcodebuild -project $SCRIPT_PATH/peridot-cradle/peridot-cradle.xcodeproj -configuration Debug build

    echo "💎  $SCRIPT_PATH/peridot-cradle/build/Debug/peridot-cradle.app"
fi

if [ $AFTER_RUN -ne 0 ]; then
    lldb $SCRIPT_PATH/peridot-cradle/build/Debug/peridot-cradle.app
fi
