[package]
name = "peridot-cradle-mac"
version = "0.1.0"
authors = ["S.Percentage <Syn.Tri.Naga@gmail.com>"]
edition = "2018"
build = "build.rs"

[lib]
crate-type = ["staticlib"]
name = "pegamelib"

[features]
UseExternalAssetPath = []
debug = ["peridot/debug"]
mt = ["peridot/mt"]

[dependencies]
bedrock = { git = "https://github.com/Pctg-x8/bedrock", branch = "peridot", features = ["VK_KHR_surface", "VK_KHR_swapchain", "Implements", "VK_MVK_macos_surface"] }
peridot = { path = "../.." }
log = "0.4"
env_logger = "0.5"
objc = "0.2"
appkit = { git = "https://github.com/Pctg-x8/appkit-rs" }
libc = "0.2"
parking_lot = "0.11"

