plugins:
  fixme:
    enabled: true
checks:
  argument-count:
    config:
      threshold: 5
  file-lines:
    config:
      threshold: 120
  nested-control-flow:
    config:
      threshold: 3
exclude_patterns:
  - "extras/"
  - "cradle/android/**/.idea/"
