dist: xenial
language: rust
sudo: required
rust:
- stable
cache: cargo
before_install:
- sudo apt-get -qq update
- sudo apt-get install -y python
script:
- python3 codeform_check.py && python3 vulnerabilities_elliminator.py && ./runtest_exclude_engine.sh
notifications:
  email: false
  webhooks:
    on_failure: always
    urls:
      secure: FtNJP/RbrirwAnehKyNKvMZ5R7xGxXZ6MJM5WqFCuLcjPs+6kkvyb3nZ1ckvVZ7XsTf0LJz6TWog3/jsco1lEvZ9byU/RmMGl+kqLezV01L8i693VOoRYnzUeLGF3NmJwUykSk75YlF1yCvPweSDCwI51/MFOd2ZS+wDBiToeQ/yFHenc20cKlFkl0DOykGb3P4b8W+d24+Lv6iUhPZXFwHchyCah5r8zZ5QXnzqqz0yziyK+a9VaEa0pBcsuiGJg/CLJ16hqEoeP98twb2qxmRbLZHuCZGcZ0uFob2jJF0Mb0pxxbWBjxvPWjIBU6oiVFe87fK07sxQSirWZ8qaXlogcmDha/kmy25MBTDGg19O5ibMcKLDOF3GLnJLQ+HZJ4qMfHMN9eJU+XpMnovNWSDquTueTgrx+1wC/Ftu6fGSHf/7RNvj0Oy7VOiGk5fwshJJd0+nqR8ChLdF3XUj1YZSqnS3/lJgfB4m097cFdX5ruPcB5Z/Kgpk5bgFT/TJAXvzyNFS6FzVO9/D1v0mptZyHNyquNbKWRKJPmXlBD1iSBOakU/xF+8+oAz2Mc9/X2XucqJLpPSF1PPeuejWr51M4GQTiniSGw+JdS/25KIZ7JGLltAlX/M/3aFZg8s2uO6AwOYfzGcZzn2wJ2bPHlrRQA8QQ/vecXVUAU8tmQc=
