[package]
name = "peridot"
description = "Peridot Engine"
version = "0.1.0"
authors = ["S.Percentage <Syn.Tri.Naga@gmail.com>"]
edition = "2018"

[dependencies]
pathfinder_partitioner = { git = "https://github.com/Pctg-x8/pathfinder" }
log = "*"
libc = "*"
bedrock = { git = "https://github.com/Pctg-x8/bedrock", branch = "peridot", features = ["Presentation", "Implements"] }
num = "*"

peridot-archive = { path = "archive" }
peridot-math = { path = "math" }

[target.'cfg(debug_assertions)'.dependencies.bedrock]
git = "https://github.com/Pctg-x8/bedrock"
branch = "peridot"
features = ["Presentation", "Implements", "VK_EXT_debug_report"]

[workspace]
exclude = ["extras/", "cradle/", "examples/"]
members = [
    "archive",
    "serialization-utils",
    "vertex-processing-pack",
    "math",
    "image",
    "vg",
    "derive",
    "tools/shaderbuild",
    "tools/archiver",
    "tools/cli",
]
