[package]
name = "peridot"
description = "Peridot Engine"
version = "0.1.0"
authors = ["S.Percentage <Syn.Tri.Naga@gmail.com>"]
edition = "2018"

[dependencies]
pathfinder_partitioner = { path = "extras/pathfinder/partitioner" }
log = "*"
libc = "*"
rayon = "1.0"
num_cpus = "1.0"

peridot-vertex-processing-pack = { path = "vertex-processing-pack" }
peridot-archive = { path = "archive" }
bedrock = { git = "https://github.com/Pctg-x8/bedrock", features = ["Presentation", "Implements"] }
peridot-math = { path = "math" }

[workspace]
exclude = ["extras/"]
members = [
    "archive", "serialization-utils", "vertex-processing-pack", "math",
    "cradle/android", "tools/shaderbuild", "cradle/linux", "cradle/windows", "cradle/mac",
    "tools/archiver"
]
