[workspace]
resolver = "2"
exclude = ["extras/", "cradle/", "examples/", "tools/"]
members = [
    "base",
    "derive",
    "modules/archive",
    "modules/serialization-utils",
    "modules/vertex-processing-pack",
    "modules/math",
    "modules/image",
    "modules/vg",
    "modules/transition",
    "modules/command-object",
    "modules/memory-manager",
]

[workspace.dependencies]
bedrock = { git = "https://github.com/Pctg-x8/bedrock", branch = "peridot" }
tracing = "0.1"
async-std = "1.13"
futures-util = "0.3"
cfg-if = "1.0"
