[package]
name = "peridot"
description = "Peridot Engine"
version = "0.1.0"
authors = ["S.Percentage <Syn.Tri.Naga@gmail.com>"]
edition = "2018"

[dependencies]
pathfinder_partitioner = { git = "https://github.com/Pctg-x8/pathfinder" }
log = "*"
libc = "*"
num = "*"

peridot-vertex-processing-pack = { path = "vertex-processing-pack" }
peridot-archive = { path = "archive" }
peridot-math = { path = "math", features = ["bedrock_interop"] }
peridot-vg = { path = "vg" }

image = "*"

[dependencies.bedrock]
git = "https://github.com/Pctg-x8/bedrock"
features = ["Presentation", "Implements", "VK_EXT_debug_report"]

[workspace]
exclude = ["extras/"]
members = [
    "archive", "serialization-utils", "vertex-processing-pack", "math", "vg", "derive",
    "cradle/android", "tools/shaderbuild", "cradle/linux", "cradle/windows", "cradle/mac",
    "tools/archiver"
]
