[workspace]
exclude = ["extras/", "cradle/", "examples/", "tools"]
members = [
    "base",
    "archive",
    "serialization-utils",
    "vertex-processing-pack",
    "math",
    "image",
    "vg",
    "derive",
    "transition",
]
