[package]
name = "peridot-marble-editor-core"
version = "0.0.1"
edition = "2024"

[features]
default = []
win32 = ["bedrock/VK_KHR_win32_surface"]
mac = ["bedrock/VK_EXT_metal_surface", "bedrock/VK_KHR_portability_enumeration"]
linux-default = ["wayland", "freetype", "fontconfig", "harfbuzz"]
wayland = ["dep:peridot-tp-wayland", "bedrock/VK_KHR_wayland_surface"]
freetype = ["dep:freetype2"]
fontconfig = ["dep:fontconfig"]
harfbuzz = ["dep:peridot-tp-harfbuzz"]

[dependencies]
bedrock = { workspace = true, features = [
    "Implements",
    "DynamicLoaded",
    "VK_KHR_surface",
    "VK_KHR_swapchain",
    "VK_EXT_debug_utils",
    "Allow1_4APIs",
] }
tracing.workspace = true
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
lyon_geom = "1.0"
freetype2 = { git = "https://github.com/Pctg-x8/ft2-rs", optional = true }
fontconfig = { git = "https://github.com/Pctg-x8/fc-rs", optional = true }
peridot-tp-harfbuzz = { path = "../../thirdparty/harfbuzz", optional = true }

[target.'cfg(windows)'.dependencies.windows]
version = "0.62"
features = [
    "Win32_UI_WindowsAndMessaging",
    "Win32_Graphics_Gdi",
    "Win32_Security",
    "Win32_System_LibraryLoader",
    "Win32_System_Threading",
    "Win32_Graphics_DirectWrite",
    "Win32_Graphics_Direct2D_Common",
]

[target.'cfg(windows)'.dependencies]
windows-core = "*"
windows-numerics = "*"

[dependencies.peridot-tp-wayland]
path = "../../thirdparty/wayland"
optional = true
features = ["tracing", "xdg-shell"]

[target.'cfg(target_os = "linux")'.dependencies]
linux-eventfd = { path = "../../platform/linux/eventfd" }
linux-epoll = { path = "../../platform/linux/epoll" }

[target.'cfg(target_os = "macos")'.dependencies]
apple-sdk-port = { path = "../../thirdparty/apple-sdk-port" }

[lints]
workspace = true
