[package]
name = "peridot-marble-editor-core"
version = "0.0.1"
edition = "2024"

[features]
default = []
win32 = ["bedrock/VK_KHR_win32_surface"]
mac = ["bedrock/VK_EXT_metal_surface", "bedrock/VK_KHR_portability_enumeration"]
linux-default = ["wayland", "freetype", "fontconfig", "harfbuzz"]
wayland = ["dep:peridot-tp-wayland", "bedrock/VK_KHR_wayland_surface"]
freetype = ["dep:peridot-tp-freetype"]
fontconfig = ["dep:peridot-tp-fontconfig"]
harfbuzz = ["dep:peridot-tp-harfbuzz"]

[dependencies]
bedrock = { workspace = true, features = [
    "Implements",
    "DynamicLoaded",
    "VK_KHR_surface",
    "VK_KHR_swapchain",
    "VK_EXT_debug_utils",
    "Allow1_4APIs",
] }
tracing.workspace = true
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
lyon_geom = "1.0"
peridot-math = { path = "../../modules/math" }
peridot-tp-freetype = { path = "../../thirdparty/freetype", optional = true }
peridot-tp-fontconfig = { path = "../../thirdparty/fontconfig", optional = true }
peridot-tp-harfbuzz = { path = "../../thirdparty/harfbuzz", optional = true }
peridot-tp-budoux = { path = "../../thirdparty/budoux", features = ["embedded-ja_knbc"] }
peridot-tp-unicode-properties = { path = "../../thirdparty/unicode-properties" }
bitflags = "2.10.0"
uuid = { version = "1.22.0", features = ["v4"] }
unicode-segmentation = "1"

[target.'cfg(windows)'.dependencies.windows]
version = "0.62"
features = [
    "Win32_UI_Controls",
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_UI_HiDpi",
    "Win32_Graphics_Gdi",
    "Win32_Security",
    "Win32_Storage_Packaging_Appx",
    "Win32_System_Diagnostics_Debug",
    "Win32_System_LibraryLoader",
    "Win32_System_Threading",
    "Win32_System_WinRT",
    "Win32_Graphics_DirectWrite",
    "Win32_Graphics_Direct2D_Common",
    "Win32_Graphics_Dwm",
    "Win32_Globalization",
    "Win32_System_WinRT_Composition",
    "System",
    "Globalization",
    "Graphics_Effects",
    "UI_Composition",
    "UI_Composition_Desktop",
    "UI_Text_Core",
    "UI_ViewManagement",
]

[target.'cfg(windows)'.dependencies]
windows-core = "*"
windows-numerics = "*"

[dependencies.peridot-tp-wayland]
path = "../../thirdparty/wayland"
optional = true
features = [
    "tracing",
    "xdg-shell",
    "wlr-layer-shell-unstable-v1",
    "single-pixel-buffer-v1",
    "viewporter",
    "kde-blur",
    "kde-appmenu",
    "kde-shadow",
    "xdg-decoration-unstable-v1",
    "text-input-unstable-v3",
    "cursor-shape-v1",
    "fractional-scale-v1",
    "alpha-modifier-v1"
]

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[target.'cfg(target_os = "linux")'.dependencies]
linux-eventfd = { path = "../../platform/linux/eventfd" }
linux-epoll = { path = "../../platform/linux/epoll" }
linux-input = { path = "../../platform/linux/input" }
peridot-tp-dbus = { path = "../../thirdparty/dbus" }
peridot-tp-xkbcommon = { path = "../../thirdparty/xkbcommon" }

[target.'cfg(target_os = "macos")'.dependencies]
apple-sdk-port = { path = "../../thirdparty/apple-sdk-port" }

[lints]
workspace = true
