param(
    [parameter(Mandatory=$true, HelpMessage="User Game Project Directory")][String]$UserlibDirectory,
    [parameter(HelpMessage="An structure name of entry point of the game")][String]$EntryTyName = "Game",
    [switch]$Run = $false,
    [parameter(HelpMessage="Asset Directory")][String]$AssetDirectory
)

$ErrorActionPreference = "Stop"
$ScriptPath = Split-Path -Parent $MyInvocation.MyCommand.Path
$ApkPackageID = "com.cterm2.infinitesweeper"
$AppBuildScript = "$ScriptPath\apkbuild\app\build.gradle"

function Sync-Userlib([string]$userlibBase, [string]$cradleBase) {
    Write-Host "Syncing Userlib Source from $userlibBase..."
    Rename-Item $cradleBase\src\userlib\glib.rs lib.rs -ErrorAction SilentlyContinue
    robocopy $userlibBase\src $cradleBase\src\userlib /mir
    Rename-Item $cradleBase\src\userlib\lib.rs glib.rs
    "//! Auto Generated by build script
    
    mod glib; pub use self::glib::$EntryTyName as Game;" | Set-Content $cradleBase\src\userlib.rs -Encoding UTF8
}
function Build([string]$scriptPath, [string[]]$defaultFeatures, [string]$assetDirectory) {
    $features = $defaultFeatures
    if ($assetDirectory) {
        $Env:PERIDOT_EXTERNAL_ASSET_PATH = $(Resolve-Path $assetDirectory).Path
        $features += "UseExternalAssetPath"
    }

    try {
        Push-Location; Set-Location $scriptPath
        cargo build --features $($features -join ",")
    }
    finally { Pop-Location }
}

Sync-Userlib $UserlibDirectory $ScriptPath
(Get-Content $AppBuildScript).replace("**APKAPPID**", "'$ApkPackageID'") | Set-Content $AppBuildScript

# Fix for Android build system's platform triple
Rename-Item $ScriptPath/../target/arm64-v8a-linux-android aarch64-linux-android -ErrorAction SilentlyContinue

# Build Userlib
$Env:RUSTFLAGS="-C link-arg=--sysroot=$Env:ANDROID_HOME\ndk-bundle\platforms\android-$Env:ANDROID_NDK_PLATFORM_TARGET\arch-arm64"
Build $ScriptPath "bedrock/VK_EXT_debug_report","bedrock/VK_KHR_android_surface","bedrock/DynamicLoaded" $AssetDirectory

# Fix for Android build system's platform triple
Rename-Item $ScriptPath/../target/aarch64-linux-android arm64-v8a-linux-android

if ($Run) {
    # Run on Android (require to connection)
    try {
        Push-Location
        Set-Location $ScriptPath/apkbuild
        ./gradlew assembleDebug
        adb install app/build/outputs/apk/debug/app-debug.apk
        adb shell am start -n $ApkPackageID/android.app.NativeActivity
    }
    finally { Pop-Location }
}
