[package]
name = "peridot-cradle-android"
version = "0.1.0"
authors = ["S.Percentage <Syn.Tri.Naga@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]
name = "pegamelib"

[features]
debug = ["peridot/debug"]
mt = ["peridot/mt"]

[dependencies]
peridot = { path = "../.." }
bedrock = { git = "https://github.com/Pctg-x8/bedrock", branch = "peridot", features = ["Implements", "Presentation", "VK_KHR_android_surface", "DynamicLoaded"] }
android = { git = "https://github.com/Pctg-x8/android-defs-rs" }
log = "0.4"
libc = "0.2"
android_logger = "0.5"
libloading = "0.5"
oboe = "0.1"
jni = "0.15"
