//! impl 4.4

#version 450

const uint IntegrationSteps = 128;
layout(local_size_x = 32, local_size_y = 32) in;

layout(set = 0, binding = 0, rgba16f) writeonly uniform image2D transmittanceLUT;

#include "precompute_common.glsl"

void main()
{
    // uv of center of texel
    const vec2 uv = (gl_GlobalInvocationID.xy + 0.5) / vec2(imageSize(transmittanceLUT));
    // Inverse Parameterization
    const float observerHeight = calcHeightFromParam(uv.y);
    const float sunZenithCos = calcSunZenithCosFromParam(uv.x);

    const vec2 observerPos = vec2(0.0f, R_EARTH + observerHeight);
    // sin^2 + cos^2 = 1
    // sin^2 = 1 - cos^2
    // sin = sqrt(1 - cos^2)
    const vec2 dir = directionFromZenithCos(sunZenithCos);
    vec2 pBound;
    const bool hasGroundIntersection = intersection(observerPos, dir, pBound);

    const float stepSize = length(pBound - observerPos) / float(IntegrationSteps);
    vec3 lastDensity = vec3(0.0);
    vec3 totalDensity = vec3(0.0);
    for (uint i = 0; i < IntegrationSteps; i++)
    {
        const vec2 s = observerPos + dir * (stepSize * float(i));
        const vec3 currentDensity = vec3(getMieDensity(height(s)), getRayleighDensity(height(s)), getOzoneDensity(height(s)));
        totalDensity += (currentDensity + lastDensity) * 0.5 * stepSize;
        lastDensity = currentDensity;
    }
    const vec3 transmittance = exp(-(totalDensity.x * MieExtinctionCoeffs + totalDensity.y * RayleighExtinctionCoeffs + totalDensity.z * OzoneExtinctionCoeffs));

    imageStore(transmittanceLUT, ivec2(gl_GlobalInvocationID.xy), hasGroundIntersection ? vec4(0.0, 0.0, 0.0, 1.0) : vec4(transmittance, 1.0));
}
