[package]
name = "peridot-math"
version = "0.1.0"
authors = ["S.Percentage <Syn.Tri.Naga@gmail.com>"]
edition = "2018"

[features]
default = ["bedrock-interop", "euclid-interop"]
bedrock-interop = ["dep:bedrock"]
euclid-interop = ["dep:euclid"]

[lints]
workspace = true

[dependencies]
bedrock = { workspace = true, optional = true }
euclid = { version = "0.19", optional = true }
