[package]
name = "peridot-gltf-loader"
version = "0.1.0"
authors = ["S.Percentage <Syn.Tri.Naga@gmail.com>"]
edition = "2018"

[dependencies]
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
serde_repr = "0.1"
bedrock = { git = "https://github.com/Pctg-x8/bedrock" }
