[package]
name = "peridot-shaderbuild"
version = "0.1.0"
description = "Combined Shader Script to Combined SPIR-V Builder for Peridot Engine"
authors = ["S.Percentage <Syn.Tri.Naga@gmail.com>"]
edition = "2021"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
bedrock.workspace = true
regex = "1.11"
peridot-vertex-processing-pack = { path = "../../modules/vertex-processing-pack", default-features = false }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }
thiserror = "2.0.3"
