[package]
name = "marble-editor-win"
description = "Peridot Marble Editor for Windows(Prototype)"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
windows-bindgen = "0.56"

[build-dependencies]
winres = "0.1"

[dependencies]
windows-core = "0.56.0"
bedrock = { git = "https://github.com/Pctg-x8/bedrock", branch = "peridot", features = [
    "Implements",
    "Allow1_3APIs",
    "VK_EXT_debug_utils",
    "VK_KHR_external_memory",
    "VK_KHR_external_memory_win32",
    "VK_KHR_synchronization2",
    "VK_KHR_external_memory_capabilities",
    "VK_KHR_get_physical_device_properties2",
    "VK_KHR_line_rasterization",
] }
widestring = "0.4"
peridot = { path = "../../base" }
peridot-math = { path = "../../modules/math" }
peridot-memory-manager = { path = "../../modules/memory-manager" }

[dependencies.windows]
version = "0.56.0"
features = [
    "Win32_System_LibraryLoader",
    "Win32_Graphics_Gdi",
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_HiDpi",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_UI_Controls",
    "Win32_System_WinRT",
    "Win32_System_WinRT_Composition",
    "Win32_System_WinRT_Graphics_Direct2D",
    "Win32_System_Threading",
    "Win32_Graphics_Direct3D",
    "Win32_Graphics_Direct2D",
    "Win32_Graphics_Direct2D_Common",
    "Win32_Graphics_Direct3D11",
    "Win32_Graphics_Direct3D12",
    "Win32_Graphics_DirectWrite",
    "Win32_Graphics_Dxgi",
    "Win32_Graphics_Dxgi_Common",
    "Win32_Graphics_Dwm",
    "Win32_Graphics_CompositionSwapchain",
    "Win32_Graphics_DirectComposition",
    "Win32_Security",
    "Win32_Storage_Packaging_Appx",
    "Foundation_Numerics",
    "Foundation_Collections",
    "System",
    "UI_Core",
    "UI_Composition",
    "UI_Composition_Desktop",
    "UI_Composition_Diagnostics",
    "Graphics_DirectX",
    "Graphics_DirectX_Direct3D11",
    "Graphics_Effects",
    "implement",
]
