[package]
name = "peridot-archive"
version = "0.1.0"
authors = ["S.Percentage <Syn.Tri.Naga@gmail.com>"]
edition = "2024"

[features]
default = []

async-rt-async-std = [
    "peridot-serialization-utils/async-rt-async-std",
    "dep:async-std",
]

[lints]
workspace = true

[dependencies]
crc = "1.8"
lz4-compression = "0.6"
libflate = "0.1"
zstd = "0.4"
peridot-serialization-utils = { path = "../serialization-utils" }
async-std = { workspace = true, optional = true }
xxhash-rust = { version = "0.8", features = ["xxh3"] }
bitflags = "2.8"

[target.'cfg(target_os = "linux")'.dependencies]
linux-io-uring = { path = "../../platform/linux/io_uring" }

[target.'cfg(windows)'.dependencies.windows]
version = "0.59"
features = [
    "Win32_Storage_FileSystem",
    "Win32_Security",
    "Win32_System_IO",
    "Win32_System_Memory",
    "Win32_System_SystemInformation",
    "Win32_System_Threading",
]

[target.'cfg(target_os = "android")'.dependencies]
crossbeam-deque = "0.8"
android = { git = "https://github.com/Pctg-x8/android-defs-rs" }
libc = "0.2"

[target.'cfg(unix)'.dependencies]
libc = "0.2"
