[package]
name = "peridot-vg"
version = "0.1.0"
authors = ["S.Percentage <Syn.Tri.Naga@gmail.com>"]

[dependencies]
pathfinder_partitioner = { path = "../extras/pathfinder/partitioner" }
font-kit = { git = "https://github.com/pcwalton/font-kit" }
lyon_path = "*"
