[package]
name = "peridot-cradle-linux"
version = "0.1.0"
authors = ["S.Percentage <Syn.Tri.Naga@gmail.com>"]
edition = "2018"

[features]
UseExternalAssetPath = []

[dependencies]
peridot = { path = "../.." }
bedrock = { git = "https://github.com/Pctg-x8/bedrock", branch = "peridot", features = ["VK_KHR_xcb_surface"] }
log = "0.4"
env_logger = "0.5"
xcb = "0.8"
pulseaudio-rs = { git = "https://github.com/Pctg-x8/pars" }

#%KERNEL_CRATE_NAME% = { path = "%KERNEL_CRATE_PATH%" }

[dependencies.async-std]
version = "1.0"
