[package]
name = "peridot-cradle-linux"
version = "0.1.0"
authors = ["S.Percentage <Syn.Tri.Naga@gmail.com>"]
edition = "2024"

[features]
UseExternalAssetPath = []
IterationBuild = []
debug = ["peridot/debug"]
mt = ["peridot/mt"]
support-xcb = ["dep:xcb", "bedrock/VK_KHR_xcb_surface"]

[dependencies]
peridot = { path = "../../base" }
bedrock = { git = "https://github.com/Pctg-x8/bedrock", branch = "peridot", features = [
    "VK_KHR_wayland_surface",
] }
xcb = { version = "1.1", optional = true }
pulseaudio-rs = { git = "https://github.com/Pctg-x8/pars" }
libc = "0.2"
regex = "1.4"
peridot-tp-wayland = { path = "../../thirdparty/wayland", features = [
    "tracing",
    "xdg-shell",
    "xdg-decoration-unstable-v1",
    "wlr-output-management-unstable-v1",
] }
pipewire = "0.7.0"
libspa-sys = "0.7.0"
parking_lot = "0.12.1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }

[dependencies.async-std]
version = "1.13"
features = ["attributes"]
