[package]
name = "peridot-cradle-linux"
version = "0.1.0"
authors = ["S.Percentage <Syn.Tri.Naga@gmail.com>"]
edition = "2018"

[features]
UseExternalAssetPath = []
IterationBuild = []
debug = ["peridot/debug"]
mt = ["peridot/mt"]

[dependencies]
peridot = { path = "../../base" }
bedrock = { git = "https://github.com/Pctg-x8/bedrock", branch = "peridot", features = [
    "VK_KHR_xcb_surface",
    "VK_KHR_wayland_surface",
] }
xcb = "1.1"
pulseaudio-rs = { git = "https://github.com/Pctg-x8/pars" }
libc = "0.2"
regex = "1.4"
wayland-backend = { version = "0.1.2", features = ["client_system"] }
wayland-client = "0.30.2"
wayland-protocols = { version = "0.30.0", features = [
    "client",
    "staging",
    "unstable",
] }
pipewire = "0.7.0"
libspa-sys = "0.7.0"
parking_lot = "0.12.1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }

[dependencies.async-std]
version = "1.0"
