[package]
name = "linux-wayland"
version = "0.1.0"
edition = "2021"

[features]
UseExternalAssetPath = []
IterationBuild = []
debug = ["peridot/debug"]
mt = ["peridot/mt"]

[dependencies]
wayland-client = "0.30.2"
peridot = { path = "../../" }
bedrock = { git = "https://github.com/Pctg-x8/bedrock", branch = "peridot", features = ["VK_KHR_wayland_surface"] }
smol = "1.3.0"
futures-util = "0.3.28"
wayland-protocols = { version = "0.30.0", features = ["client", "unstable", "staging"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
wayland-backend = { version = "0.1.2", features = ["client_system"] }
