[package]
name = "linux-wayland"
version = "0.1.0"
edition = "2021"

[features]
UseExternalAssetPath = []
IterationBuild = []
debug = ["peridot/debug"]
mt = ["peridot/mt"]

[dependencies]
wayland-client = "0.30.2"
peridot = { path = "../../" }
bedrock = { git = "https://github.com/Pctg-x8/bedrock", branch = "peridot", features = ["VK_KHR_wayland_surface"] }
