[package]
name = "peridot-cradle-direct"
version = "0.1.0"
authors = ["S.Percentage <Syn.Tri.Naga@gmail.com>"]
edition = "2018"

[features]
UseExternalAssetPath = []

[dependencies]
peridot = { path = "../.." }
bedrock = { git = "https://github.com/Pctg-x8/bedrock", branch = "peridot", features = ["VK_KHR_xcb_surface", "VK_KHR_display", "VK_KHR_external_memory_fd"] }
log = "0.4"
env_logger = "0.5"
xcb = "0.8"
libc = "0.2"
regex = "1.4"
once_cell = "1.5"

#%KERNEL_CRATE_NAME% = { path = "%KERNEL_CRATE_PATH%" }
