//
//  AppDelegate.swift
//  peridot-cradle-mac: AppDelegate(For Autogenerated main)
//
//  Created by S.Percentage on 2018/12/02.
//  Copyright © 2018 S.Percentage. All rights reserved.
//

import Cocoa
import AVFAudio

@NSApplicationMain
final class AppDelegate : NSObject, NSApplicationDelegate {
    func applicationShouldTerminate(_ sender: NSApplication) -> NSApplication.TerminateReply {
        NSApplication.TerminateReply.terminateLater
    }
}
