[package]
name = "peridot-marble-editor-mac"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["staticlib"]
name = "peridot_marble_editor"

[features]
enable-profiling = ["peridot-marble-editor-core/enable-profiling"]

[dependencies]
peridot-marble-editor-core = { path = "../core", features = ["mac"] }
