[package]
name = "box-ui"
version = "0.1.0"
edition = "2021"

[features]
default = []
use-freetype = ["peridot-vg/use-freetype"]
use-fontconfig = ["peridot-vg/use-fontconfig"]

[dependencies]
peridot = { path = "../../base", features = ["mt"] }
peridot-vertex-processing-pack = { path = "../../modules/vertex-processing-pack", features = [
    "with-loader-impl",
] }
peridot-memory-manager = { path = "../../modules/memory-manager" }
peridot-vg = { path = "../../modules/vg" }
peridot-rendering-configuration = { path = "../../modules/rendering-configuration", features = ["with-loader-impl"] }
bedrock = { git = "https://github.com/Pctg-x8/bedrock", branch = "peridot" }
