[package]
name = "peridot-rendering-configuration-compiler"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { workspace = true, features = ["derive"] }
peridot-rendering-configuration = { path  = "../../modules/rendering-configuration", features = ["compilation"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter", "fmt"] }
