// Bindings generated by `windows-bindgen` 0.66.0

#![allow(
    non_snake_case,
    non_upper_case_globals,
    non_camel_case_types,
    dead_code,
    clippy::all
)]

pub mod Microsoft {
    pub mod Graphics {
        pub mod Canvas {
            windows_core::imp::define_interface!(
                ICanvasImage,
                ICanvasImage_Vtbl,
                0x794966d3_6a64_47e9_8da8_b46aaa24d53b
            );
            impl windows_core::RuntimeType for ICanvasImage {
                const SIGNATURE: windows_core::imp::ConstBuffer =
                    windows_core::imp::ConstBuffer::for_interface::<Self>();
            }
            windows_core::imp::interface_hierarchy!(
                ICanvasImage,
                windows_core::IUnknown,
                windows_core::IInspectable
            );
            windows_core::imp::required_hierarchy!(
                ICanvasImage,
                windows::Foundation::IClosable,
                windows::Graphics::Effects::IGraphicsEffectSource
            );
            impl ICanvasImage {
                pub fn Close(&self) -> windows_core::Result<()> {
                    let this =
                        &windows_core::Interface::cast::<windows::Foundation::IClosable>(self)?;
                    unsafe {
                        (windows_core::Interface::vtable(this).Close)(
                            windows_core::Interface::as_raw(this),
                        )
                        .ok()
                    }
                }
            }
            impl windows_core::RuntimeName for ICanvasImage {
                const NAME: &'static str = "Microsoft.Graphics.Canvas.ICanvasImage";
            }
            pub trait ICanvasImage_Impl:
                windows::Foundation::IClosable_Impl
                + windows::Graphics::Effects::IGraphicsEffectSource_Impl
            {
            }
            impl ICanvasImage_Vtbl {
                pub const fn new<Identity: ICanvasImage_Impl, const OFFSET: isize>() -> Self {
                    Self {
                        base__: windows_core::IInspectable_Vtbl::new::<
                            Identity,
                            ICanvasImage,
                            OFFSET,
                        >(),
                        GetBounds: 0,
                        GetBoundsWithTransform: 0,
                    }
                }
                pub fn matches(iid: &windows_core::GUID) -> bool {
                    iid == &<ICanvasImage as windows_core::Interface>::IID
                }
            }
            #[repr(C)]
            #[doc(hidden)]
            pub struct ICanvasImage_Vtbl {
                pub base__: windows_core::IInspectable_Vtbl,
                GetBounds: usize,
                GetBoundsWithTransform: usize,
            }
            pub mod Effects {
                #[repr(transparent)]
                #[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
                pub struct EffectOptimization(pub i32);
                impl EffectOptimization {
                    pub const Speed: Self = Self(0i32);
                    pub const Balanced: Self = Self(1i32);
                    pub const Quality: Self = Self(2i32);
                }
                impl windows_core::TypeKind for EffectOptimization {
                    type TypeKind = windows_core::CopyType;
                }
                impl windows_core::RuntimeType for EffectOptimization {
                    const SIGNATURE: windows_core::imp::ConstBuffer =
                        windows_core::imp::ConstBuffer::from_slice(
                            b"enum(Microsoft.Graphics.Canvas.Effects.EffectOptimization;i4)",
                        );
                }
                #[repr(transparent)]
                #[derive(Clone, Debug, Eq, PartialEq)]
                pub struct GaussianBlurEffect(windows_core::IUnknown);
                windows_core::imp::interface_hierarchy!(
                    GaussianBlurEffect,
                    windows_core::IUnknown,
                    windows_core::IInspectable
                );
                windows_core::imp::required_hierarchy!(
                    GaussianBlurEffect,
                    ICanvasEffect,
                    super::ICanvasImage,
                    windows::Foundation::IClosable,
                    windows::Graphics::Effects::IGraphicsEffect,
                    windows::Graphics::Effects::IGraphicsEffectSource
                );
                impl GaussianBlurEffect {
                    pub fn new() -> windows_core::Result<Self> {
                        Self::IActivationFactory(|f| f.ActivateInstance::<Self>())
                    }
                    fn IActivationFactory<
                        R,
                        F: FnOnce(&windows_core::imp::IGenericFactory) -> windows_core::Result<R>,
                    >(
                        callback: F,
                    ) -> windows_core::Result<R> {
                        static SHARED: windows_core::imp::FactoryCache<
                            GaussianBlurEffect,
                            windows_core::imp::IGenericFactory,
                        > = windows_core::imp::FactoryCache::new();
                        SHARED.call(callback)
                    }
                    pub fn CacheOutput(&self) -> windows_core::Result<bool> {
                        let this = &windows_core::Interface::cast::<ICanvasEffect>(self)?;
                        unsafe {
                            let mut result__ = core::mem::zeroed();
                            (windows_core::Interface::vtable(this).CacheOutput)(
                                windows_core::Interface::as_raw(this),
                                &mut result__,
                            )
                            .map(|| result__)
                        }
                    }
                    pub fn SetCacheOutput(&self, value: bool) -> windows_core::Result<()> {
                        let this = &windows_core::Interface::cast::<ICanvasEffect>(self)?;
                        unsafe {
                            (windows_core::Interface::vtable(this).SetCacheOutput)(
                                windows_core::Interface::as_raw(this),
                                value,
                            )
                            .ok()
                        }
                    }
                    pub fn Close(&self) -> windows_core::Result<()> {
                        let this =
                            &windows_core::Interface::cast::<windows::Foundation::IClosable>(self)?;
                        unsafe {
                            (windows_core::Interface::vtable(this).Close)(
                                windows_core::Interface::as_raw(this),
                            )
                            .ok()
                        }
                    }
                    pub fn BlurAmount(&self) -> windows_core::Result<f32> {
                        let this = self;
                        unsafe {
                            let mut result__ = core::mem::zeroed();
                            (windows_core::Interface::vtable(this).BlurAmount)(
                                windows_core::Interface::as_raw(this),
                                &mut result__,
                            )
                            .map(|| result__)
                        }
                    }
                    pub fn SetBlurAmount(&self, value: f32) -> windows_core::Result<()> {
                        let this = self;
                        unsafe {
                            (windows_core::Interface::vtable(this).SetBlurAmount)(
                                windows_core::Interface::as_raw(this),
                                value,
                            )
                            .ok()
                        }
                    }
                    pub fn Optimization(&self) -> windows_core::Result<EffectOptimization> {
                        let this = self;
                        unsafe {
                            let mut result__ = core::mem::zeroed();
                            (windows_core::Interface::vtable(this).Optimization)(
                                windows_core::Interface::as_raw(this),
                                &mut result__,
                            )
                            .map(|| result__)
                        }
                    }
                    pub fn SetOptimization(
                        &self,
                        value: EffectOptimization,
                    ) -> windows_core::Result<()> {
                        let this = self;
                        unsafe {
                            (windows_core::Interface::vtable(this).SetOptimization)(
                                windows_core::Interface::as_raw(this),
                                value,
                            )
                            .ok()
                        }
                    }
                    pub fn Source(
                        &self,
                    ) -> windows_core::Result<windows::Graphics::Effects::IGraphicsEffectSource>
                    {
                        let this = self;
                        unsafe {
                            let mut result__ = core::mem::zeroed();
                            (windows_core::Interface::vtable(this).Source)(
                                windows_core::Interface::as_raw(this),
                                &mut result__,
                            )
                            .and_then(|| windows_core::Type::from_abi(result__))
                        }
                    }
                    pub fn SetSource<P0>(&self, source: P0) -> windows_core::Result<()>
                    where
                        P0: windows_core::Param<windows::Graphics::Effects::IGraphicsEffectSource>,
                    {
                        let this = self;
                        unsafe {
                            (windows_core::Interface::vtable(this).SetSource)(
                                windows_core::Interface::as_raw(this),
                                source.param().abi(),
                            )
                            .ok()
                        }
                    }
                    pub fn Name(&self) -> windows_core::Result<windows_core::HSTRING> {
                        let this = &windows_core::Interface::cast::<
                            windows::Graphics::Effects::IGraphicsEffect,
                        >(self)?;
                        unsafe {
                            let mut result__ = core::mem::zeroed();
                            (windows_core::Interface::vtable(this).Name)(
                                windows_core::Interface::as_raw(this),
                                &mut result__,
                            )
                            .map(|| core::mem::transmute(result__))
                        }
                    }
                    pub fn SetName(
                        &self,
                        name: &windows_core::HSTRING,
                    ) -> windows_core::Result<()> {
                        let this = &windows_core::Interface::cast::<
                            windows::Graphics::Effects::IGraphicsEffect,
                        >(self)?;
                        unsafe {
                            (windows_core::Interface::vtable(this).SetName)(
                                windows_core::Interface::as_raw(this),
                                core::mem::transmute_copy(name),
                            )
                            .ok()
                        }
                    }
                }
                impl windows_core::RuntimeType for GaussianBlurEffect {
                    const SIGNATURE: windows_core::imp::ConstBuffer =
                        windows_core::imp::ConstBuffer::for_class::<Self, IGaussianBlurEffect>();
                }
                unsafe impl windows_core::Interface for GaussianBlurEffect {
                    type Vtable = <IGaussianBlurEffect as windows_core::Interface>::Vtable;
                    const IID: windows_core::GUID =
                        <IGaussianBlurEffect as windows_core::Interface>::IID;
                }
                impl windows_core::RuntimeName for GaussianBlurEffect {
                    const NAME: &'static str =
                        "Microsoft.Graphics.Canvas.Effects.GaussianBlurEffect";
                }
                unsafe impl Send for GaussianBlurEffect {}
                unsafe impl Sync for GaussianBlurEffect {}
                windows_core::imp::define_interface!(
                    ICanvasEffect,
                    ICanvasEffect_Vtbl,
                    0x0ef96f8c_9b5e_4bf0_a399_aad8ce53db55
                );
                impl windows_core::RuntimeType for ICanvasEffect {
                    const SIGNATURE: windows_core::imp::ConstBuffer =
                        windows_core::imp::ConstBuffer::for_interface::<Self>();
                }
                windows_core::imp::interface_hierarchy!(
                    ICanvasEffect,
                    windows_core::IUnknown,
                    windows_core::IInspectable
                );
                windows_core::imp::required_hierarchy!(
                    ICanvasEffect,
                    super::ICanvasImage,
                    windows::Foundation::IClosable,
                    windows::Graphics::Effects::IGraphicsEffect,
                    windows::Graphics::Effects::IGraphicsEffectSource
                );
                impl ICanvasEffect {
                    pub fn CacheOutput(&self) -> windows_core::Result<bool> {
                        let this = self;
                        unsafe {
                            let mut result__ = core::mem::zeroed();
                            (windows_core::Interface::vtable(this).CacheOutput)(
                                windows_core::Interface::as_raw(this),
                                &mut result__,
                            )
                            .map(|| result__)
                        }
                    }
                    pub fn SetCacheOutput(&self, value: bool) -> windows_core::Result<()> {
                        let this = self;
                        unsafe {
                            (windows_core::Interface::vtable(this).SetCacheOutput)(
                                windows_core::Interface::as_raw(this),
                                value,
                            )
                            .ok()
                        }
                    }
                    pub fn Close(&self) -> windows_core::Result<()> {
                        let this =
                            &windows_core::Interface::cast::<windows::Foundation::IClosable>(self)?;
                        unsafe {
                            (windows_core::Interface::vtable(this).Close)(
                                windows_core::Interface::as_raw(this),
                            )
                            .ok()
                        }
                    }
                    pub fn Name(&self) -> windows_core::Result<windows_core::HSTRING> {
                        let this = &windows_core::Interface::cast::<
                            windows::Graphics::Effects::IGraphicsEffect,
                        >(self)?;
                        unsafe {
                            let mut result__ = core::mem::zeroed();
                            (windows_core::Interface::vtable(this).Name)(
                                windows_core::Interface::as_raw(this),
                                &mut result__,
                            )
                            .map(|| core::mem::transmute(result__))
                        }
                    }
                    pub fn SetName(
                        &self,
                        name: &windows_core::HSTRING,
                    ) -> windows_core::Result<()> {
                        let this = &windows_core::Interface::cast::<
                            windows::Graphics::Effects::IGraphicsEffect,
                        >(self)?;
                        unsafe {
                            (windows_core::Interface::vtable(this).SetName)(
                                windows_core::Interface::as_raw(this),
                                core::mem::transmute_copy(name),
                            )
                            .ok()
                        }
                    }
                }
                impl windows_core::RuntimeName for ICanvasEffect {
                    const NAME: &'static str = "Microsoft.Graphics.Canvas.Effects.ICanvasEffect";
                }
                pub trait ICanvasEffect_Impl:
                    super::ICanvasImage_Impl
                    + windows::Foundation::IClosable_Impl
                    + windows::Graphics::Effects::IGraphicsEffect_Impl
                    + windows::Graphics::Effects::IGraphicsEffectSource_Impl
                {
                    fn CacheOutput(&self) -> windows_core::Result<bool>;
                    fn SetCacheOutput(&self, value: bool) -> windows_core::Result<()>;
                }
                impl ICanvasEffect_Vtbl {
                    pub const fn new<Identity: ICanvasEffect_Impl, const OFFSET: isize>() -> Self {
                        unsafe extern "system" fn CacheOutput<
                            Identity: ICanvasEffect_Impl,
                            const OFFSET: isize,
                        >(
                            this: *mut core::ffi::c_void,
                            result__: *mut bool,
                        ) -> windows_core::HRESULT {
                            unsafe {
                                let this: &Identity = &*((this as *const *const ()).offset(OFFSET)
                                    as *const Identity);
                                match ICanvasEffect_Impl::CacheOutput(this) {
                                    Ok(ok__) => {
                                        result__.write(core::mem::transmute_copy(&ok__));
                                        windows_core::HRESULT(0)
                                    }
                                    Err(err) => err.into(),
                                }
                            }
                        }
                        unsafe extern "system" fn SetCacheOutput<
                            Identity: ICanvasEffect_Impl,
                            const OFFSET: isize,
                        >(
                            this: *mut core::ffi::c_void,
                            value: bool,
                        ) -> windows_core::HRESULT {
                            unsafe {
                                let this: &Identity = &*((this as *const *const ()).offset(OFFSET)
                                    as *const Identity);
                                ICanvasEffect_Impl::SetCacheOutput(this, value).into()
                            }
                        }
                        Self {
                            base__: windows_core::IInspectable_Vtbl::new::<
                                Identity,
                                ICanvasEffect,
                                OFFSET,
                            >(),
                            CacheOutput: CacheOutput::<Identity, OFFSET>,
                            SetCacheOutput: SetCacheOutput::<Identity, OFFSET>,
                            BufferPrecision: 0,
                            SetBufferPrecision: 0,
                            InvalidateSourceRectangle: 0,
                            GetInvalidRectangles: 0,
                            GetRequiredSourceRectangle: 0,
                            GetRequiredSourceRectangles: 0,
                        }
                    }
                    pub fn matches(iid: &windows_core::GUID) -> bool {
                        iid == &<ICanvasEffect as windows_core::Interface>::IID
                    }
                }
                #[repr(C)]
                #[doc(hidden)]
                pub struct ICanvasEffect_Vtbl {
                    pub base__: windows_core::IInspectable_Vtbl,
                    pub CacheOutput: unsafe extern "system" fn(
                        *mut core::ffi::c_void,
                        *mut bool,
                    )
                        -> windows_core::HRESULT,
                    pub SetCacheOutput: unsafe extern "system" fn(
                        *mut core::ffi::c_void,
                        bool,
                    )
                        -> windows_core::HRESULT,
                    BufferPrecision: usize,
                    SetBufferPrecision: usize,
                    InvalidateSourceRectangle: usize,
                    GetInvalidRectangles: usize,
                    GetRequiredSourceRectangle: usize,
                    GetRequiredSourceRectangles: usize,
                }
                windows_core::imp::define_interface!(
                    IGaussianBlurEffect,
                    IGaussianBlurEffect_Vtbl,
                    0xa82ec394_6734_5830_9123_2c82b27dd3c0
                );
                impl windows_core::RuntimeType for IGaussianBlurEffect {
                    const SIGNATURE: windows_core::imp::ConstBuffer =
                        windows_core::imp::ConstBuffer::for_interface::<Self>();
                }
                #[repr(C)]
                #[doc(hidden)]
                pub struct IGaussianBlurEffect_Vtbl {
                    pub base__: windows_core::IInspectable_Vtbl,
                    pub BlurAmount: unsafe extern "system" fn(
                        *mut core::ffi::c_void,
                        *mut f32,
                    )
                        -> windows_core::HRESULT,
                    pub SetBlurAmount: unsafe extern "system" fn(
                        *mut core::ffi::c_void,
                        f32,
                    )
                        -> windows_core::HRESULT,
                    pub Optimization: unsafe extern "system" fn(
                        *mut core::ffi::c_void,
                        *mut EffectOptimization,
                    )
                        -> windows_core::HRESULT,
                    pub SetOptimization: unsafe extern "system" fn(
                        *mut core::ffi::c_void,
                        EffectOptimization,
                    )
                        -> windows_core::HRESULT,
                    BorderMode: usize,
                    SetBorderMode: usize,
                    pub Source: unsafe extern "system" fn(
                        *mut core::ffi::c_void,
                        *mut *mut core::ffi::c_void,
                    )
                        -> windows_core::HRESULT,
                    pub SetSource: unsafe extern "system" fn(
                        *mut core::ffi::c_void,
                        *mut core::ffi::c_void,
                    )
                        -> windows_core::HRESULT,
                }
            }
        }
    }
}
