[workspace]
resolver = "2"
members = ["archiver", "cli", "shaderbuild", "semantic-shaderbuild", "rendering-configuration-compiler", "rendering-configuration-reader", "asset-processor"]

[workspace.dependencies]
bedrock = { git = "https://github.com/Pctg-x8/bedrock", branch = "peridot" }
clap = "4.5"
tracing = "0.1"
tracing-subscriber = "0.3"
thiserror = "2.0"

