[package]
name = "peridot-asset-processor"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { workspace = true, features = ["derive"] }
image = "0.25.8"
ktx = { path = "../../thirdparty/ktx" }
bedrock = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["fmt", "env-filter"] }
thiserror = { workspace = true }
