[package]
name = "peridot-cradle-windows"
version = "0.1.0"
authors = ["S.Percentage <Syn.Tri.Naga@gmail.com>"]
edition = "2018"
build = "build.rs"

[features]
UseExternalAssetPath = []
transparent = ["comdrive", "metrics", "widestring", "bedrock/VK_KHR_external_memory_win32", "bedrock/VK_KHR_external_semaphore_win32"]
IterationBuild = []
debug = ["peridot/debug"]
mt = ["peridot/mt"]

[dependencies]
bedrock = { git = "https://github.com/Pctg-x8/bedrock", branch = "peridot", features = ["Presentation", "Implements", "VK_KHR_win32_surface"] }
peridot = { path = "../.." }
log = "0.4"
env_logger = "0.5"
rayon = "1.0"
num_cpus = "1.0"
comdrive = { git = "https://github.com/Pctg-x8/comdrive", optional = true }
metrics = { git = "https://github.com/Pctg-x8/metrics", optional = true }
widestring = { version = "0.4", optional = true }
parking_lot = "0.11"

[dependencies.windows]
version = "0.43"
features = [
    "Win32_Foundation",
    "Win32_System_LibraryLoader",
    "Win32_System_Com",
    "Win32_Graphics_Gdi",
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_HiDpi",
    "Win32_Media_Audio",
    "Win32_UI_Shell_PropertiesSystem",
    "Win32_System_Com_StructuredStorage",
    "Win32_Devices_FunctionDiscovery",
    "Win32_Media_KernelStreaming",
    "Win32_Media_Multimedia",
    "Win32_UI_Input",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_UI_Input_XboxController"
]
