[package]
name = "peridot-cradle-windows"
version = "0.1.0"
authors = ["S.Percentage <Syn.Tri.Naga@gmail.com>"]
edition = "2018"
build = "build.rs"

[features]
UseExternalAssetPath = []

[dependencies]
bedrock = { git = "https://github.com/Pctg-x8/bedrock" }
peridot = { path = "../.." }
log = "0.4"
env_logger = "0.5"
rayon = "1.0"
num_cpus = "1.0"
#%KERNEL_CRATE_NAME% = { path = "%KERNEL_CRATE_PATH%" }

[dependencies.winapi]
version = "0.3"
features = [
    "winuser", "libloaderapi", "mmdeviceapi", "combaseapi", "propsys", "coml2api", "devpkey", "objbase",
    "audioclient", "ksmedia"
]
