#version 450

layout(set = 0, binding = 0, rgba16f) readonly uniform image3D src;
layout(set = 0, binding = 1, rgba16f) uniform image3D dest;

layout(local_size_x = 8, local_size_y = 8, local_size_z = 8) in;
void main()
{
    const vec4 v = imageLoad(src, ivec3(gl_GlobalInvocationID.xyz)) + imageLoad(dest, ivec3(gl_GlobalInvocationID.xyz));
    imageStore(dest, ivec3(gl_GlobalInvocationID.xyz), v);
}
