name: Integrity Check
on:
  pull_request:
    types: ["opened", "synchronize"]
jobs:
  preconditions:
    name: "Preconditions"
    runs-on: ubuntu-latest
    outputs:
      begintime: ${{ steps.begintime.outputs.begintime }}
      has_code_changes: ${{ steps.fileck.outputs.has_code_changes }}
    steps:
      - name: Getting begintime
        id: begintime
        run: |
          echo "::set-output name=begintime::$(date +%s)"
      - name: Checking Changed Filenames
        id: fileck
        run: |
          HAS_CODE_CHANGES=0
          QUERY_STRING='query($cursor: String) { repository(owner: \"${{ github.event.repository.owner.login }}\", name: \"${{ github.event.repository.name }}\") { pullRequest(number: ${{ github.event.number }}) { files(first: 50, after: $cursor) { nodes { path }, pageInfo { hasNextPage, endCursor } } } } }'
          QUERY_CURSOR='null'
          while :; do
            POSTDATA="{ \"query\": \"$QUERY_STRING\", \"variables\": { \"cursor\": $QUERY_CURSOR }\" } }"
            echo $POSTDATA
            API_RESPONSE=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -X POST -d "$POSTDATA" https://api.github.com/graphql)
            echo $API_RESPONSE
            echo $API_RESPONSE | jq ".data.repository.pullRequest.files.nodes[].path" | grep -qE '\.rs"$|Cargo(\.template)?\.toml"$' && :
            if [[ $? == 0 ]]; then HAS_CODE_CHANGES=1; break; fi
            HAS_NEXT_PAGE=$(echo $API_RESPONSE | jq ".data.repository.pullRequest.files.pageInfo.hasNextPage")
            if [[ "$HAS_NEXT_PAGE" == "true" ]]; then
              QUERY_CURSOR=$(echo $API_RESPONSE | jq ".data.repository.pullRequest.files.pageInfo.endCursor")
            else
              break
            fi
          done < <(cat)
          echo "::set-output name=has_code_changes::$HAS_CODE_CHANGES"
  check-formats:
    name: "Code Formats"
    runs-on: ubuntu-latest
    needs: preconditions
    if: ${{ needs.preconditions.outputs.has_code_changes == 1 }}
    steps:
      - name: Checking out(HEAD commit)
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Checking out
        uses: actions/checkout@v2
      - name: "Running Check: LineWidth"
        uses: ./.github/actions/codeform-checker
        with:
          script: codeform_check
      - name: "Running Check: Vulnerabilities"
        uses: ./.github/actions/codeform-checker
        with:
          script: vulnerabilities_elliminator
      - name: Notify as Failure
        uses: ./.github/actions/integrity-check-slack-notifier
        if: failure()
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_SECRET }}
          AWS_DEFAULT_REGION: "ap-northeast-1"
        with:
          status: failure
          failure_step: check-formats
          begintime: ${{ needs.preconditions.outputs.begintime }}
          head_sha: ${{ github.event.pull_request.head.sha }}
          base_sha: ${{ github.event.pull_request.base.sha }}
          pr_number: ${{ github.event.number }}
          pr_title: ${{ github.event.pull_request.title }}
  check-baselayer:
    name: "Base Layer"
    runs-on: ubuntu-latest
    needs: preconditions
    if: ${{ needs.preconditions.outputs.has_code_changes == 1 }}
    steps:
      - name: Checking out(HEAD commit)
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Checking out
        uses: actions/checkout@v2
      - name: Building as Checking
        uses: ./.github/actions/checkbuild-baselayer
      # - name: Uploading Build Artifacts
      #   uses: actions/upload-artifact@v1
      #   if: success()
      #   with:
      #     name: "Peridot IntegrityCheck BuildCache"
      #     path: .buildcache
      - name: Notify as Failure
        uses: ./.github/actions/integrity-check-slack-notifier
        if: failure()
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_SECRET }}
          AWS_DEFAULT_REGION: "ap-northeast-1"
        with:
          status: failure
          failure_step: check-baselayer
          begintime: ${{ needs.preconditions.outputs.begintime }}
          head_sha: ${{ github.event.pull_request.head.sha }}
          base_sha: ${{ github.event.pull_request.base.sha }}
          pr_number: ${{ github.event.number }}
          pr_title: ${{ github.event.pull_request.title }}
  check-tools:
    name: "Tools"
    runs-on: ubuntu-latest
    needs: [preconditions, check-baselayer]
    if: ${{ needs.preconditions.outputs.has_code_changes == 1 }}
    steps:
      - name: Checking out(HEAD commit)
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Checking out
        uses: actions/checkout@v2
      # - name: Downloading last Build Artifacts
      #   uses: actions/download-artifact@v1
      #   with:
      #     name: "Peridot IntegrityCheck BuildCache"
      #     path: .buildcache
      - name: Building as Checking
        uses: ./.github/actions/checkbuild-subdir
        with:
          path: tools
      - name: Notify as Failure
        uses: ./.github/actions/integrity-check-slack-notifier
        if: failure()
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_SECRET }}
          AWS_DEFAULT_REGION: "ap-northeast-1"
        with:
          status: failure
          failure_step: check-tools
          begintime: ${{ needs.preconditions.outputs.begintime }}
          head_sha: ${{ github.event.pull_request.head.sha }}
          base_sha: ${{ github.event.pull_request.base.sha }}
          pr_number: ${{ github.event.number }}
          pr_title: ${{ github.event.pull_request.title }}
  check-modules:
    name: "Modules"
    runs-on: ubuntu-latest
    needs: [preconditions, check-baselayer]
    if: ${{ needs.preconditions.outputs.has_code_changes == 1 }}
    steps:
      - name: Checking out(HEAD commit)
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Checking out
        uses: actions/checkout@v2
      # - name: Downloading last Build Artifacts
      #   uses: actions/download-artifact@v1
      #   with:
      #     name: "Peridot IntegrityCheck BuildCache"
      #     path: .buildcache
      - name: Building as Checking
        uses: ./.github/actions/checkbuild-subdir
        with:
          path: .
      # - name: Uploading Build Artifacts
      #   uses: actions/upload-artifact@v1
      #   if: success()
      #   with:
      #     name: "Peridot IntegrityCheck BuildCache"
      #     path: .buildcache
      - name: Notify as Failure
        uses: ./.github/actions/integrity-check-slack-notifier
        if: failure()
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_SECRET }}
          AWS_DEFAULT_REGION: "ap-northeast-1"
        with:
          status: failure
          failure_step: check-modules
          begintime: ${{ needs.preconditions.outputs.begintime }}
          head_sha: ${{ github.event.pull_request.head.sha }}
          base_sha: ${{ github.event.pull_request.base.sha }}
          pr_number: ${{ github.event.number }}
          pr_title: ${{ github.event.pull_request.title }}
  check-examples:
    name: "Examples"
    runs-on: ubuntu-latest
    needs: [preconditions, check-modules]
    if: ${{ needs.preconditions.outputs.has_code_changes == 1 }}
    steps:
      - name: Checking out(HEAD commit)
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Checking out
        uses: actions/checkout@v2
      # - name: Downloading last Build Artifacts
      #   uses: actions/download-artifact@v1
      #   with:
      #     name: "Peridot IntegrityCheck BuildCache"
      #     path: .buildcache
      - name: Building as Checking
        uses: ./.github/actions/checkbuild-subdir
        with:
          path: examples
      - name: Notify as Success
        uses: ./.github/actions/integrity-check-slack-notifier
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_SECRET }}
          AWS_DEFAULT_REGION: "ap-northeast-1"
        with:
          status: success
          begintime: ${{ needs.preconditions.outputs.begintime }}
          head_sha: ${{ github.event.pull_request.head.sha }}
          base_sha: ${{ github.event.pull_request.base.sha }}
          pr_number: ${{ github.event.number }}
          pr_title: ${{ github.event.pull_request.title }}
      - name: Notify as Failure
        uses: ./.github/actions/integrity-check-slack-notifier
        if: failure()
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_SECRET }}
          AWS_DEFAULT_REGION: "ap-northeast-1"
        with:
          status: failure
          failure_step: check-examples
          begintime: ${{ needs.preconditions.outputs.begintime }}
          head_sha: ${{ github.event.pull_request.head.sha }}
          base_sha: ${{ github.event.pull_request.base.sha }}
          pr_number: ${{ github.event.number }}
          pr_title: ${{ github.event.pull_request.title }}