jobs:
  "check-baselayer":
    name: Base Layer
    needs:
    - preconditions
    "runs-on": "ubuntu-latest"
    steps:
    - if: 'true'
      name: "Checking out (HEAD commit)"
      uses: "actions/checkout@v2"
      with:
        ref: "${{ github.event.pull_request.head.sha }}"
    - if: 'true'
      name: Checking out
      uses: "actions/checkout@v2"
    - if: 'true'
      name: Initialize Cache
      uses: "actions/cache@v2"
      with:
        key: "${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}"
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
    - if: 'true'
      name: Building as Checking
      uses: "./.github/actions/checkbuild-baselayer"
    - env:
        AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
        AWS_DEFAULT_REGION: "ap-northeast-1"
        AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_ACCESS_SECRET }}"
      if: "failure()"
      name: Notify as Failure
      uses: "Pctg-x8/ci-notifications-post-invoker@master"
      with:
        begintime: "${{ needs.preconditions.outputs.begintime }}"
        failure_step: "check-baselayer"
        mode: branch
        report_name: Weekly Check
        status: failure
  "check-cradle-macos":
    name: "Cradle(macOS)"
    needs:
    - preconditions
    - "check-baselayer"
    "runs-on": "macos-latest"
    steps:
    - if: 'true'
      name: "Checking out (HEAD commit)"
      uses: "actions/checkout@v2"
      with:
        ref: "${{ github.event.pull_request.head.sha }}"
    - if: 'true'
      name: Checking out
      uses: "actions/checkout@v2"
    - if: 'true'
      name: Initialize Cache
      uses: "actions/cache@v2"
      with:
        key: "${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}"
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
    - if: 'true'
      name: install requirements
      run: brew install coreutils
    - env:
        VK_SDK_PATH: ''
      if: 'true'
      name: cargo check
      run: "./build.sh mac examples/basic --RunChecks 2>&1 | tee $GITHUB_WORKSPACE/.buildlog"
      shell: bash
    - env:
        AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
        AWS_DEFAULT_REGION: "ap-northeast-1"
        AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_ACCESS_SECRET }}"
      if: "failure()"
      name: Notify as Failure
      uses: "Pctg-x8/ci-notifications-post-invoker@master"
      with:
        begintime: "${{ needs.preconditions.outputs.begintime }}"
        failure_step: "check-cradle-macos"
        mode: branch
        report_name: Weekly Check
        status: failure
  "check-cradle-windows":
    name: "Cradle(Windows)"
    needs:
    - preconditions
    - "check-baselayer"
    "runs-on": "windows-latest"
    steps:
    - if: 'true'
      name: "Checking out (HEAD commit)"
      uses: "actions/checkout@v2"
      with:
        ref: "${{ github.event.pull_request.head.sha }}"
    - if: 'true'
      name: Checking out
      uses: "actions/checkout@v2"
    - if: 'true'
      name: Initialize Cache
      uses: "actions/cache@v2"
      with:
        key: "${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}"
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
    - env:
        VK_SDK_PATH: ''
      if: 'true'
      name: cargo check
      run: |
        $ErrorActionPreference = "Continue"
        pwsh -c './build.ps1 windows examples/basic -RunTests -Features bedrock/DynamicLoaded' *>&1 | Tee-Object $Env:GITHUB_WORKSPACE/.buildlog
    - env:
        VK_SDK_PATH: ''
      if: 'true'
      name: "cargo check for transparent-back"
      run: |
            $ErrorActionPreference = "Continue"
            pwsh -c './build.ps1 windows examples/basic -RunTests -Features "transparent,bedrock/DynamicLoaded"' *>&1 | Tee-Object $Env:GITHUB_WORKSPACE/.buildlog
    - env:
        AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
        AWS_DEFAULT_REGION: "ap-northeast-1"
        AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_ACCESS_SECRET }}"
      if: "failure()"
      name: Notify as Failure
      uses: "Pctg-x8/ci-notifications-post-invoker@master"
      with:
        begintime: "${{ needs.preconditions.outputs.begintime }}"
        failure_step: "check-cradle-windows"
        mode: branch
        report_name: Weekly Check
        status: failure
  "check-examples":
    name: Examples
    needs:
    - preconditions
    - "check-modules"
    "runs-on": "ubuntu-latest"
    steps:
    - if: 'true'
      name: "Checking out (HEAD commit)"
      uses: "actions/checkout@v2"
      with:
        ref: "${{ github.event.pull_request.head.sha }}"
    - if: 'true'
      name: Checking out
      uses: "actions/checkout@v2"
    - if: 'true'
      name: Initialize Cache
      uses: "actions/cache@v2"
      with:
        key: "${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}"
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
    - if: 'true'
      name: Building as Checking
      uses: "./.github/actions/checkbuild-subdir"
      with:
        path: examples
    - env:
        AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
        AWS_DEFAULT_REGION: "ap-northeast-1"
        AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_ACCESS_SECRET }}"
      if: "failure()"
      name: Notify as Failure
      uses: "Pctg-x8/ci-notifications-post-invoker@master"
      with:
        begintime: "${{ needs.preconditions.outputs.begintime }}"
        failure_step: "check-examples"
        mode: branch
        report_name: Weekly Check
        status: failure
  "check-formats":
    name: Code Formats
    needs:
    - preconditions
    "runs-on": "ubuntu-latest"
    steps:
    - if: 'true'
      name: "Checking out (HEAD commit)"
      uses: "actions/checkout@v2"
      with:
        ref: "${{ github.event.pull_request.head.sha }}"
    - if: 'true'
      name: Checking out
      uses: "actions/checkout@v2"
    - if: 'true'
      name: "Running Check: Line Width"
      uses: "./.github/actions/codeform-checker"
      with:
        script: codeform_check
    - if: 'true'
      name: "Running Check: Debugging Weaks"
      uses: "./.github/actions/codeform-checker"
      with:
        script: vulnerabilities_elliminator
    - if: 'true'
      name: "Running Check: Trailing Newline for Source Code Files"
      uses: "./.github/actions/codeform-checker"
      with:
        script: trailing_newline_checker
    - env:
        AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
        AWS_DEFAULT_REGION: "ap-northeast-1"
        AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_ACCESS_SECRET }}"
      if: "failure()"
      name: Notify as Failure
      uses: "Pctg-x8/ci-notifications-post-invoker@master"
      with:
        begintime: "${{ needs.preconditions.outputs.begintime }}"
        failure_step: "check-formats"
        mode: branch
        report_name: Weekly Check
        status: failure
  "check-modules":
    name: Modules
    needs:
    - preconditions
    - "check-baselayer"
    "runs-on": "ubuntu-latest"
    steps:
    - if: 'true'
      name: "Checking out (HEAD commit)"
      uses: "actions/checkout@v2"
      with:
        ref: "${{ github.event.pull_request.head.sha }}"
    - if: 'true'
      name: Checking out
      uses: "actions/checkout@v2"
    - if: 'true'
      name: Initialize Cache
      uses: "actions/cache@v2"
      with:
        key: "${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}"
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
    - if: 'true'
      name: Building as Checking
      uses: "./.github/actions/checkbuild-subdir"
      with:
        path: '.'
    - env:
        AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
        AWS_DEFAULT_REGION: "ap-northeast-1"
        AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_ACCESS_SECRET }}"
      if: "failure()"
      name: Notify as Failure
      uses: "Pctg-x8/ci-notifications-post-invoker@master"
      with:
        begintime: "${{ needs.preconditions.outputs.begintime }}"
        failure_step: "check-modules"
        mode: branch
        report_name: Weekly Check
        status: failure
  "check-tools":
    name: Tools
    needs:
    - preconditions
    - "check-baselayer"
    "runs-on": "ubuntu-latest"
    steps:
    - if: 'true'
      name: "Checking out (HEAD commit)"
      uses: "actions/checkout@v2"
      with:
        ref: "${{ github.event.pull_request.head.sha }}"
    - if: 'true'
      name: Checking out
      uses: "actions/checkout@v2"
    - if: 'true'
      name: Initialize Cache
      uses: "actions/cache@v2"
      with:
        key: "${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}"
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
    - if: 'true'
      name: Building as Checking
      uses: "./.github/actions/checkbuild-subdir"
      with:
        path: tools
    - env:
        AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
        AWS_DEFAULT_REGION: "ap-northeast-1"
        AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_ACCESS_SECRET }}"
      if: "failure()"
      name: Notify as Failure
      uses: "Pctg-x8/ci-notifications-post-invoker@master"
      with:
        begintime: "${{ needs.preconditions.outputs.begintime }}"
        failure_step: "check-tools"
        mode: branch
        report_name: Weekly Check
        status: failure
  preconditions:
    name: Preconditions
    outputs:
      begintime: "${{ steps.begintime.outputs.begintime }}"
    "runs-on": "ubuntu-latest"
    steps:
    - id: begintime
      name: Getting begintime
      run: "echo \"::set-output name=begintime::$(date +%s)\""
  "report-success":
    name: Report as Success
    needs:
    - preconditions
    - "check-examples"
    - "check-formats"
    - "check-cradle-windows"
    - "check-cradle-macos"
    "runs-on": "ubuntu-latest"
    steps:
    - name: "Checking out (HEAD commit)"
      uses: "actions/checkout@v2"
      with:
        ref: "${{ github.event.pull_request.head.sha }}"
    - name: Checking out
      uses: "actions/checkout@v2"
    - env:
        AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
        AWS_DEFAULT_REGION: "ap-northeast-1"
        AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_ACCESS_SECRET }}"
      name: Notify as Success
      uses: "Pctg-x8/ci-notifications-post-invoker@master"
      with:
        begintime: "${{ needs.preconditions.outputs.begintime }}"
        mode: branch
        report_name: Weekly Check
        status: success
name: "Integrity Check (Weekly)"
'on':
  schedule:
  - cron: "0 12 * * wed"
