jobs:
  check-baselayer:
    name: Base Layer
    needs:
      - preconditions
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - if: 'true'
        name: Checking out
        uses: "actions/checkout@v5"
        with:
          submodules: recursive
      - if: 'true'
        name: Initialize Cache
        uses: "actions/cache@v4"
        with:
          key: "${{ runner.os }}-cargo-${{ hashFiles('**/*.rs', '**/Cargo.toml') }}"
          path: "~/.cargo/registry\n~/.cargo/git\ntarget\ntools/target"
          restore-keys: "${{ runner.os }}-cargo-"
      - if: 'true'
        name: Setup cargo-json-gha-translator
        run: "mkdir -p $HOME/.local/bin && curl -o $HOME/.local/bin/cargo-json-gha-translator -L \\\n  https://github.com/Pctg-x8/cargo-json-gha-translator/releases/download/v0.1.3/cargo-json-gha-translator\nchmod +x $HOME/.local/bin/cargo-json-gha-translator"
      - if: 'true'
        name: check
        run: "set -o pipefail\ncargo check --package peridot --verbose --features=bedrock/VK_EXT_debug_report --message-format=json | $HOME/.local/bin/cargo-json-gha-translator"
      - if: 'true'
        name: "check(mt)"
        run: "set -o pipefail\ncargo check --package peridot --verbose --features=bedrock/VK_EXT_debug_report,mt --message-format=json | $HOME/.local/bin/cargo-json-gha-translator"
      - if: "failure()"
        uses: "actions/checkout@v5"
        with:
          ref: "${{ github.event.pull_request.head.sha }}"
      - if: "failure()"
        name: Configure for Slack Notification
        uses: "aws-actions/configure-aws-credentials@v4"
        with:
          aws-region: ap-northeast-1
          role-to-assume: arn:aws:iam::208140986057:role/GHALambdaInvoker
      - if: "failure()"
        name: Notify as Failure
        uses: "Pctg-x8/ci-notifications-post-invoker@master"
        with:
          begintime: "${{ needs.preconditions.outputs.begintime }}"
          failure_step: Base Layer
          mode: branch
          report_name: Weekly Check
          status: failure
  check-cradle-android:
    env:
      PERIDOT_BUILD_TP_KTX_SKIP_CMAKE: '1'
      PERIDOT_BUILD_TP_SLANG_LIB_PATH: "${{ format('{0}/thirdparty/slang/source-repo/build/Release/lib', github.workspace) }}"
      PERIDOT_BUILD_TP_SLANG_SKIP_CMAKE: '1'
    name: "Cradle(Android)"
    needs:
      - check-baselayer
      - check-examples
      - check-modules
      - check-tools
      - preconditions
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - if: 'true'
        name: Disable man-db triggers for apt-get
        run: "echo \"set man-db/auto-update false\" | debconf-communicate\ndpkg-reconfigure man-db"
      - if: 'true'
        name: Checking out
        uses: "actions/checkout@v5"
        with:
          submodules: recursive
      - if: 'true'
        name: Initialize Cache
        uses: "actions/cache@v4"
        with:
          key: "${{ runner.os }}-cargo-${{ hashFiles('**/*.rs', '**/Cargo.toml') }}"
          path: "~/.cargo/registry\n~/.cargo/git\ntarget\ntools/target"
          restore-keys: "${{ runner.os }}-cargo-"
      - if: 'true'
        name: Cache ccache artifacts
        uses: "actions/cache@v4"
        with:
          key: "${{ runner.os }}-ccache-${{ hashFiles('thirdparty/slang/source-repo/**/*.c', 'thirdparty/slang/source-repo/**/*.h', 'thirdparty/slang/source-repo/**/*.cpp', 'thirdparty/slang/source-repo/**/*.hpp', 'thirdparty/slang/source-repo/**/*.inl', 'thirdparty/ktx/source-repo/**/*.c', 'thirdparty/ktx/source-repo/**/*.h', 'thirdparty/ktx/source-repo/**/*.cpp', 'thirdparty/ktx/source-repo/**/*.hpp', 'thirdparty/ktx/source-repo/**/*.inl') }}"
          path: "~/.cache/ccache"
          restore-keys: "${{ runner.os }}-ccache-"
      - if: 'true'
        name: Install ccache
        run: "sudo apt-get update && sudo apt-get install ccache"
      - if: 'true'
        name: "Pre-build c deps(slang)"
        run: "cmake --preset default -G Ninja -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_C_COMPILER_LAUNCHER=ccache -DSLANG_ENABLE_SLANG_RHI=FALSE -DSLANG_ENABLE_GFX=FALSE -DSLANG_ENABLE_SLANGD=FALSE -DSLANG_ENABLE_SLANGC=FALSE -DSLANG_ENABLE_SLANGI=FALSE -DSLANG_ENABLE_SLANGRT=FALSE -DSLANG_ENABLE_TESTS=FALSE -DSLANG_ENABLE_EXAMPLES=FALSE && cmake --build --preset releaseWithDebugInfo"
        working-directory: thirdparty/slang/source-repo
      - if: 'true'
        name: "Pre-build c deps(ktx)"
        run: "cmake . -B build -G Ninja -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_C_COMPILER_LAUNCHER=ccache -DKTX_FEATURE_TESTS=OFF -DKTX_FEATURE_VK_UPLOAD=OFF -DKTX_FEATURE_GL_UPLOAD=OFF -DKTX_FEATURE_TOOLS=OFF && cmake --build build"
        working-directory: thirdparty/ktx/source-repo
      - if: 'true'
        name: Setup Rust for Android
        uses: "actions-rs/toolchain@v1"
        with:
          target: aarch64-linux-android
          toolchain: stable
      - if: 'true'
        name: Setup Java
        uses: "actions/setup-java@v3"
        with:
          distribution: adopt
          java-version: '17'
      - if: 'true'
        name: install cargo-ndk
        run: cargo install cargo-ndk
      - if: 'true'
        name: Build CLI
        run: cargo build
        working-directory: "./tools/cli"
      - env:
          LD_LIBRARY_PATH: "${{ format('{0}/thirdparty/slang/source-repo/build/Release/lib:{0}/thirdparty/ktx/source-repo/build:{1}', github.workspace, env.LD_LIBRARY_PATH) }}"
          NDK_PLATFORM_TARGET: '28'
          PERIDOT_CLI_BUILTIN_ASSETS_PATH: "${{ format('{0}/builtin-assets', github.workspace) }}"
          PERIDOT_CLI_CRADLE_BASE: "${{ format('{0}/cradle', github.workspace) }}"
        if: 'true'
        name: cargo check
        run: "./tools/target/debug/peridot check examples/image-plane -p android 2>&1 | tee $GITHUB_WORKSPACE/.buildlog"
        shell: bash
      - if: "failure()"
        uses: "actions/checkout@v5"
        with:
          ref: "${{ github.event.pull_request.head.sha }}"
      - if: "failure()"
        name: Configure for Slack Notification
        uses: "aws-actions/configure-aws-credentials@v4"
        with:
          aws-region: ap-northeast-1
          role-to-assume: arn:aws:iam::208140986057:role/GHALambdaInvoker
      - if: "failure()"
        name: Notify as Failure
        uses: "Pctg-x8/ci-notifications-post-invoker@master"
        with:
          begintime: "${{ needs.preconditions.outputs.begintime }}"
          failure_step: "Cradle(Android)"
          mode: branch
          report_name: Weekly Check
          status: failure
  check-cradle-linux:
    env:
      PERIDOT_BUILD_TP_KTX_SKIP_CMAKE: '1'
      PERIDOT_BUILD_TP_SLANG_LIB_PATH: "${{ format('{0}/thirdparty/slang/source-repo/build/Release/lib', github.workspace) }}"
      PERIDOT_BUILD_TP_SLANG_SKIP_CMAKE: '1'
    name: "Cradle(Linux)"
    needs:
      - check-baselayer
      - check-examples
      - check-modules
      - check-tools
      - preconditions
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - if: 'true'
        name: Disable man-db triggers for apt-get
        run: "echo \"set man-db/auto-update false\" | debconf-communicate\ndpkg-reconfigure man-db"
      - if: 'true'
        name: Add External PPA
        run: sudo apt-add-repository -y ppa:pipewire-debian/pipewire-upstream
      - if: 'true'
        name: Install extra packages
        run: "sudo apt-get update && sudo apt-get install -y libwayland-dev libpipewire-0.3-dev libspa-0.2-dev"
      - if: 'true'
        name: Checking out
        uses: "actions/checkout@v5"
        with:
          submodules: recursive
      - if: 'true'
        name: Initialize Cache
        uses: "actions/cache@v4"
        with:
          key: "${{ runner.os }}-cargo-${{ hashFiles('**/*.rs', '**/Cargo.toml') }}"
          path: "~/.cargo/registry\n~/.cargo/git\ntarget\ntools/target"
          restore-keys: "${{ runner.os }}-cargo-"
      - if: 'true'
        name: Cache ccache artifacts
        uses: "actions/cache@v4"
        with:
          key: "${{ runner.os }}-ccache-${{ hashFiles('thirdparty/slang/source-repo/**/*.c', 'thirdparty/slang/source-repo/**/*.h', 'thirdparty/slang/source-repo/**/*.cpp', 'thirdparty/slang/source-repo/**/*.hpp', 'thirdparty/slang/source-repo/**/*.inl', 'thirdparty/ktx/source-repo/**/*.c', 'thirdparty/ktx/source-repo/**/*.h', 'thirdparty/ktx/source-repo/**/*.cpp', 'thirdparty/ktx/source-repo/**/*.hpp', 'thirdparty/ktx/source-repo/**/*.inl') }}"
          path: "~/.cache/ccache"
          restore-keys: "${{ runner.os }}-ccache-"
      - if: 'true'
        name: Install ccache
        run: "sudo apt-get update && sudo apt-get install ccache"
      - if: 'true'
        name: "Pre-build c deps(slang)"
        run: "cmake --preset default -G Ninja -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_C_COMPILER_LAUNCHER=ccache -DSLANG_ENABLE_SLANG_RHI=FALSE -DSLANG_ENABLE_GFX=FALSE -DSLANG_ENABLE_SLANGD=FALSE -DSLANG_ENABLE_SLANGC=FALSE -DSLANG_ENABLE_SLANGI=FALSE -DSLANG_ENABLE_SLANGRT=FALSE -DSLANG_ENABLE_TESTS=FALSE -DSLANG_ENABLE_EXAMPLES=FALSE && cmake --build --preset releaseWithDebugInfo"
        working-directory: thirdparty/slang/source-repo
      - if: 'true'
        name: "Pre-build c deps(ktx)"
        run: "cmake . -B build -G Ninja -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_C_COMPILER_LAUNCHER=ccache -DKTX_FEATURE_TESTS=OFF -DKTX_FEATURE_VK_UPLOAD=OFF -DKTX_FEATURE_GL_UPLOAD=OFF -DKTX_FEATURE_TOOLS=OFF && cmake --build build"
        working-directory: thirdparty/ktx/source-repo
      - if: 'true'
        name: Build CLI
        run: cargo build
        working-directory: "./tools/cli"
      - env:
          LD_LIBRARY_PATH: "${{ format('{0}/thirdparty/slang/source-repo/build/Release/lib:{0}/thirdparty/ktx/source-repo/build:{1}', github.workspace, env.LD_LIBRARY_PATH) }}"
          PERIDOT_CLI_BUILTIN_ASSETS_PATH: "${{ format('{0}/builtin-assets', github.workspace) }}"
          PERIDOT_CLI_CRADLE_BASE: "${{ format('{0}/cradle', github.workspace) }}"
        if: 'true'
        name: cargo check
        run: "./tools/target/debug/peridot check examples/image-plane -p linux 2>&1 | tee $GITHUB_WORKSPACE/.buildlog"
        shell: bash
      - if: "failure()"
        uses: "actions/checkout@v5"
        with:
          ref: "${{ github.event.pull_request.head.sha }}"
      - if: "failure()"
        name: Configure for Slack Notification
        uses: "aws-actions/configure-aws-credentials@v4"
        with:
          aws-region: ap-northeast-1
          role-to-assume: arn:aws:iam::208140986057:role/GHALambdaInvoker
      - if: "failure()"
        name: Notify as Failure
        uses: "Pctg-x8/ci-notifications-post-invoker@master"
        with:
          begintime: "${{ needs.preconditions.outputs.begintime }}"
          failure_step: "Cradle(Linux)"
          mode: branch
          report_name: Weekly Check
          status: failure
  check-cradle-macos:
    env:
      PERIDOT_BUILD_TP_KTX_SKIP_CMAKE: '1'
      PERIDOT_BUILD_TP_SLANG_LIB_PATH: "${{ format('{0}/thirdparty/slang/source-repo/build/Release/lib', github.workspace) }}"
      PERIDOT_BUILD_TP_SLANG_SKIP_CMAKE: '1'
    name: "Cradle(macOS)"
    needs:
      - check-baselayer
      - check-examples
      - check-modules
      - check-tools
      - preconditions
    permissions:
      id-token: write
    runs-on: macos-latest
    steps:
      - if: 'true'
        name: Checking out
        uses: "actions/checkout@v5"
        with:
          submodules: recursive
      - if: 'true'
        name: Initialize Cache
        uses: "actions/cache@v4"
        with:
          key: "${{ runner.os }}-cargo-${{ hashFiles('**/*.rs', '**/Cargo.toml') }}"
          path: "~/.cargo/registry\n~/.cargo/git\ntarget\ntools/target"
          restore-keys: "${{ runner.os }}-cargo-"
      - if: 'true'
        name: Cache ccache artifacts
        uses: "actions/cache@v4"
        with:
          key: "${{ runner.os }}-ccache-${{ hashFiles('thirdparty/slang/source-repo/**/*.c', 'thirdparty/slang/source-repo/**/*.h', 'thirdparty/slang/source-repo/**/*.cpp', 'thirdparty/slang/source-repo/**/*.hpp', 'thirdparty/slang/source-repo/**/*.inl', 'thirdparty/ktx/source-repo/**/*.c', 'thirdparty/ktx/source-repo/**/*.h', 'thirdparty/ktx/source-repo/**/*.cpp', 'thirdparty/ktx/source-repo/**/*.hpp', 'thirdparty/ktx/source-repo/**/*.inl') }}"
          path: "~/Library/Caches/ccache"
          restore-keys: "${{ runner.os }}-ccache-"
      - if: 'true'
        name: Install ccache
        run: brew install ccache
      - if: 'true'
        name: "Pre-build c deps(slang)"
        run: "cmake --preset default -G Ninja -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_C_COMPILER_LAUNCHER=ccache -DSLANG_ENABLE_SLANG_RHI=FALSE -DSLANG_ENABLE_GFX=FALSE -DSLANG_ENABLE_SLANGD=FALSE -DSLANG_ENABLE_SLANGC=FALSE -DSLANG_ENABLE_SLANGI=FALSE -DSLANG_ENABLE_SLANGRT=FALSE -DSLANG_ENABLE_TESTS=FALSE -DSLANG_ENABLE_EXAMPLES=FALSE && cmake --build --preset releaseWithDebugInfo"
        working-directory: thirdparty/slang/source-repo
      - if: 'true'
        name: "Pre-build c deps(ktx)"
        run: "cmake . -B build -G Ninja -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_C_COMPILER_LAUNCHER=ccache -DKTX_FEATURE_TESTS=OFF -DKTX_FEATURE_VK_UPLOAD=OFF -DKTX_FEATURE_GL_UPLOAD=OFF -DKTX_FEATURE_TOOLS=OFF && cmake --build build"
        working-directory: thirdparty/ktx/source-repo
      - if: 'true'
        name: Build CLI
        run: cargo build
        working-directory: "./tools/cli"
      - if: 'true'
        name: Build archiver
        run: cargo build
        working-directory: "./tools/archiver"
      - if: 'true'
        name: Install requirements
        run: brew install coreutils
      - env:
          LD_LIBRARY_PATH: "${{ format('{0}/thirdparty/slang/source-repo/build/Release/lib:{0}/thirdparty/ktx/source-repo/build:{1}', github.workspace, env.LD_LIBRARY_PATH) }}"
          PERIDOT_CLI_ARCHIVER_PATH: "${{ format('{0}/tools/target/debug/peridot-archiver', github.workspace) }}"
          PERIDOT_CLI_BUILTIN_ASSETS_PATH: "${{ format('{0}/builtin-assets', github.workspace) }}"
          PERIDOT_CLI_CRADLE_BASE: "${{ format('{0}/cradle', github.workspace) }}"
          VULKAN_SDK: /Users
        if: 'true'
        name: cargo check
        run: "./tools/target/debug/peridot check examples/image-plane -p mac 2>&1 | tee $GITHUB_WORKSPACE/.buildlog"
        shell: bash
      - if: "failure()"
        uses: "actions/checkout@v5"
        with:
          ref: "${{ github.event.pull_request.head.sha }}"
      - if: "failure()"
        name: Configure for Slack Notification
        uses: "aws-actions/configure-aws-credentials@v4"
        with:
          aws-region: ap-northeast-1
          role-to-assume: arn:aws:iam::208140986057:role/GHALambdaInvoker
      - if: "failure()"
        name: Notify as Failure
        uses: "Pctg-x8/ci-notifications-post-invoker@master"
        with:
          begintime: "${{ needs.preconditions.outputs.begintime }}"
          failure_step: "Cradle(macOS)"
          mode: branch
          report_name: Weekly Check
          status: failure
  check-cradle-windows:
    env:
      PERIDOT_BUILD_TP_KTX_SKIP_CMAKE: '1'
      PERIDOT_BUILD_TP_SLANG_LIB_PATH: "${{ format('{0}/thirdparty/slang/source-repo/build/Release/lib', github.workspace) }}"
      PERIDOT_BUILD_TP_SLANG_SKIP_CMAKE: '1'
    name: "Cradle(Windows)"
    needs:
      - check-baselayer
      - check-examples
      - check-modules
      - check-tools
      - preconditions
    permissions:
      id-token: write
    runs-on: windows-latest
    steps:
      - if: 'true'
        name: Checking out
        uses: "actions/checkout@v5"
        with:
          submodules: recursive
      - if: 'true'
        name: Initialize Cache
        uses: "actions/cache@v4"
        with:
          key: "${{ runner.os }}-cargo-${{ hashFiles('**/*.rs', '**/Cargo.toml') }}"
          path: "~/.cargo/registry\n~/.cargo/git\ntarget\ntools/target"
          restore-keys: "${{ runner.os }}-cargo-"
      - if: 'true'
        name: Cache ccache artifacts
        uses: "actions/cache@v4"
        with:
          key: "${{ runner.os }}-ccache-${{ hashFiles('thirdparty/slang/source-repo/**/*.c', 'thirdparty/slang/source-repo/**/*.h', 'thirdparty/slang/source-repo/**/*.cpp', 'thirdparty/slang/source-repo/**/*.hpp', 'thirdparty/slang/source-repo/**/*.inl', 'thirdparty/ktx/source-repo/**/*.c', 'thirdparty/ktx/source-repo/**/*.h', 'thirdparty/ktx/source-repo/**/*.cpp', 'thirdparty/ktx/source-repo/**/*.hpp', 'thirdparty/ktx/source-repo/**/*.inl') }}"
          path: "~\\AppData\\Roaming\\ccache"
          restore-keys: "${{ runner.os }}-ccache-"
      - if: 'true'
        name: Install ccache
        run: choco install ccache
      - if: 'true'
        name: "Pre-build c deps(slang)"
        run: "Install-Module Pscx -Scope CurrentUser -Force -AllowClobber\nImport-VisualStudioVars -VisualStudioVersion 2022 -Architecture x64\ncmake --preset default -G Ninja -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_C_COMPILER_LAUNCHER=ccache -DSLANG_ENABLE_SLANG_RHI=FALSE -DSLANG_ENABLE_GFX=FALSE -DSLANG_ENABLE_SLANGD=FALSE -DSLANG_ENABLE_SLANGC=FALSE -DSLANG_ENABLE_SLANGI=FALSE -DSLANG_ENABLE_SLANGRT=FALSE -DSLANG_ENABLE_TESTS=FALSE -DSLANG_ENABLE_EXAMPLES=FALSE && cmake --build --preset releaseWithDebugInfo"
        working-directory: thirdparty/slang/source-repo
      - if: 'true'
        name: "Pre-build c deps(ktx)"
        run: "Install-Module Pscx -Scope CurrentUser -Force -AllowClobber\nImport-VisualStudioVars -VisualStudioVersion 2022 -Architecture x64 && cmake . -B build -G Ninja -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_C_COMPILER_LAUNCHER=ccache -DKTX_FEATURE_TESTS=OFF -DKTX_FEATURE_VK_UPLOAD=OFF -DKTX_FEATURE_GL_UPLOAD=OFF -DKTX_FEATURE_TOOLS=OFF && cmake --build build"
        working-directory: thirdparty/ktx/source-repo
      - if: 'true'
        name: Build CLI
        run: cargo build
        working-directory: "./tools/cli"
      - if: 'true'
        name: Copy thirdparty DLLs
        run: "Copy-Item -Path thirdparty/ktx/source-repo/build/Debug/ktx.dll -Destination tools/target/debug/ktx.dll\nCopy-Item -Path thirdparty/slang/source-repo/build/RelWithDebInfo/bin/slang.dll -Destination tools/target/debug/slang.dll\nCopy-Item -Path thirdparty/slang/source-repo/build/RelWithDebInfo/bin/slang-glslang.dll -Destination tools/target/debug/slang-glslang.dll"
      - env:
          PERIDOT_CLI_BUILTIN_ASSETS_PATH: "${{ format('{0}/builtin-assets', github.workspace) }}"
          PERIDOT_CLI_CRADLE_BASE: "${{ format('{0}/cradle', github.workspace) }}"
          VK_SDK_PATH: ''
        if: 'true'
        name: cargo check
        run: "$ErrorActionPreference = \"Continue\"\npwsh -c 'tools/target/debug/peridot test examples/image-plane -p windows -F bedrock/DynamicLoaded' *>&1 | Tee-Object $Env:GITHUB_WORKSPACE/.buildlog"
      - env:
          PERIDOT_CLI_BUILTIN_ASSETS_PATH: "${{ format('{0}/builtin-assets', github.workspace) }}"
          PERIDOT_CLI_CRADLE_BASE: "${{ format('{0}/cradle', github.workspace) }}"
          VK_SDK_PATH: ''
        if: 'true'
        name: cargo check for transparent-back
        run: "$ErrorActionPreference = \"Continue\"\npwsh -c 'tools/target/debug/peridot test examples/image-plane -p windows -F transparent -F bedrock/DynamicLoaded' *>&1 | Tee-Object $Env:GITHUB_WORKSPACE/.buildlog"
      - if: "failure()"
        uses: "actions/checkout@v5"
        with:
          ref: "${{ github.event.pull_request.head.sha }}"
      - if: "failure()"
        name: Configure for Slack Notification
        uses: "aws-actions/configure-aws-credentials@v4"
        with:
          aws-region: ap-northeast-1
          role-to-assume: arn:aws:iam::208140986057:role/GHALambdaInvoker
      - if: "failure()"
        name: Notify as Failure
        uses: "Pctg-x8/ci-notifications-post-invoker@master"
        with:
          begintime: "${{ needs.preconditions.outputs.begintime }}"
          failure_step: "Cradle(Windows)"
          mode: branch
          report_name: Weekly Check
          status: failure
  check-examples:
    env:
      PERIDOT_BUILD_TP_KTX_SKIP_CMAKE: '1'
      PERIDOT_BUILD_TP_SLANG_LIB_PATH: "${{ format('{0}/thirdparty/slang/source-repo/build/Release/lib', github.workspace) }}"
      PERIDOT_BUILD_TP_SLANG_SKIP_CMAKE: '1'
    name: Examples
    needs:
      - check-modules
      - check-baselayer
      - preconditions
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - if: 'true'
        name: Disable man-db triggers for apt-get
        run: "echo \"set man-db/auto-update false\" | debconf-communicate\ndpkg-reconfigure man-db"
      - if: 'true'
        name: Checking out
        uses: "actions/checkout@v5"
        with:
          submodules: recursive
      - if: 'true'
        name: Initialize Cache
        uses: "actions/cache@v4"
        with:
          key: "${{ runner.os }}-cargo-${{ hashFiles('**/*.rs', '**/Cargo.toml') }}"
          path: "~/.cargo/registry\n~/.cargo/git\ntarget\ntools/target"
          restore-keys: "${{ runner.os }}-cargo-"
      - if: 'true'
        name: Cache ccache artifacts
        uses: "actions/cache@v4"
        with:
          key: "${{ runner.os }}-ccache-${{ hashFiles('thirdparty/slang/source-repo/**/*.c', 'thirdparty/slang/source-repo/**/*.h', 'thirdparty/slang/source-repo/**/*.cpp', 'thirdparty/slang/source-repo/**/*.hpp', 'thirdparty/slang/source-repo/**/*.inl', 'thirdparty/ktx/source-repo/**/*.c', 'thirdparty/ktx/source-repo/**/*.h', 'thirdparty/ktx/source-repo/**/*.cpp', 'thirdparty/ktx/source-repo/**/*.hpp', 'thirdparty/ktx/source-repo/**/*.inl') }}"
          path: "~/.cache/ccache"
          restore-keys: "${{ runner.os }}-ccache-"
      - if: 'true'
        name: Install ccache
        run: "sudo apt-get update && sudo apt-get install ccache"
      - if: 'true'
        name: "Pre-build c deps(slang)"
        run: "cmake --preset default -G Ninja -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_C_COMPILER_LAUNCHER=ccache -DSLANG_ENABLE_SLANG_RHI=FALSE -DSLANG_ENABLE_GFX=FALSE -DSLANG_ENABLE_SLANGD=FALSE -DSLANG_ENABLE_SLANGC=FALSE -DSLANG_ENABLE_SLANGI=FALSE -DSLANG_ENABLE_SLANGRT=FALSE -DSLANG_ENABLE_TESTS=FALSE -DSLANG_ENABLE_EXAMPLES=FALSE && cmake --build --preset releaseWithDebugInfo"
        working-directory: thirdparty/slang/source-repo
      - if: 'true'
        name: "Pre-build c deps(ktx)"
        run: "cmake . -B build -G Ninja -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_C_COMPILER_LAUNCHER=ccache -DKTX_FEATURE_TESTS=OFF -DKTX_FEATURE_VK_UPLOAD=OFF -DKTX_FEATURE_GL_UPLOAD=OFF -DKTX_FEATURE_TOOLS=OFF && cmake --build build"
        working-directory: thirdparty/ktx/source-repo
      - if: 'true'
        name: Setup cargo-json-gha-translator
        run: "mkdir -p $HOME/.local/bin && curl -o $HOME/.local/bin/cargo-json-gha-translator -L \\\n  https://github.com/Pctg-x8/cargo-json-gha-translator/releases/download/v0.1.3/cargo-json-gha-translator\nchmod +x $HOME/.local/bin/cargo-json-gha-translator"
      - if: 'true'
        name: check
        run: "exec $GITHUB_WORKSPACE/.github/scripts/checkbuild-subdir.sh"
        working-directory: examples
      - if: "failure()"
        uses: "actions/checkout@v5"
        with:
          ref: "${{ github.event.pull_request.head.sha }}"
      - if: "failure()"
        name: Configure for Slack Notification
        uses: "aws-actions/configure-aws-credentials@v4"
        with:
          aws-region: ap-northeast-1
          role-to-assume: arn:aws:iam::208140986057:role/GHALambdaInvoker
      - if: "failure()"
        name: Notify as Failure
        uses: "Pctg-x8/ci-notifications-post-invoker@master"
        with:
          begintime: "${{ needs.preconditions.outputs.begintime }}"
          failure_step: Examples
          mode: branch
          report_name: Weekly Check
          status: failure
  check-formats:
    env:
      PERIDOT_BUILD_TP_KTX_SKIP_CMAKE: '1'
      PERIDOT_BUILD_TP_SLANG_LIB_PATH: "${{ format('{0}/thirdparty/slang/source-repo/build/Release/lib', github.workspace) }}"
      PERIDOT_BUILD_TP_SLANG_SKIP_CMAKE: '1'
    name: Code Formats
    needs:
      - preconditions
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - if: 'true'
        name: Disable man-db triggers for apt-get
        run: "echo \"set man-db/auto-update false\" | debconf-communicate\ndpkg-reconfigure man-db"
      - if: 'true'
        name: Checking out
        uses: "actions/checkout@v5"
        with:
          submodules: recursive
      - if: 'true'
        name: Initialize Cache
        uses: "actions/cache@v4"
        with:
          key: "${{ runner.os }}-cargo-${{ hashFiles('**/*.rs', '**/Cargo.toml') }}"
          path: "~/.cargo/registry\n~/.cargo/git\ntarget\ntools/target"
          restore-keys: "${{ runner.os }}-cargo-"
      - if: 'true'
        name: Cache ccache artifacts
        uses: "actions/cache@v4"
        with:
          key: "${{ runner.os }}-ccache-${{ hashFiles('thirdparty/slang/source-repo/**/*.c', 'thirdparty/slang/source-repo/**/*.h', 'thirdparty/slang/source-repo/**/*.cpp', 'thirdparty/slang/source-repo/**/*.hpp', 'thirdparty/slang/source-repo/**/*.inl', 'thirdparty/ktx/source-repo/**/*.c', 'thirdparty/ktx/source-repo/**/*.h', 'thirdparty/ktx/source-repo/**/*.cpp', 'thirdparty/ktx/source-repo/**/*.hpp', 'thirdparty/ktx/source-repo/**/*.inl') }}"
          path: "~/.cache/ccache"
          restore-keys: "${{ runner.os }}-ccache-"
      - if: 'true'
        name: Install ccache
        run: "sudo apt-get update && sudo apt-get install ccache"
      - if: 'true'
        name: "Pre-build c deps(slang)"
        run: "cmake --preset default -G Ninja -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_C_COMPILER_LAUNCHER=ccache -DSLANG_ENABLE_SLANG_RHI=FALSE -DSLANG_ENABLE_GFX=FALSE -DSLANG_ENABLE_SLANGD=FALSE -DSLANG_ENABLE_SLANGC=FALSE -DSLANG_ENABLE_SLANGI=FALSE -DSLANG_ENABLE_SLANGRT=FALSE -DSLANG_ENABLE_TESTS=FALSE -DSLANG_ENABLE_EXAMPLES=FALSE && cmake --build --preset releaseWithDebugInfo"
        working-directory: thirdparty/slang/source-repo
      - if: 'true'
        name: "Pre-build c deps(ktx)"
        run: "cmake . -B build -G Ninja -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_C_COMPILER_LAUNCHER=ccache -DKTX_FEATURE_TESTS=OFF -DKTX_FEATURE_VK_UPLOAD=OFF -DKTX_FEATURE_GL_UPLOAD=OFF -DKTX_FEATURE_TOOLS=OFF && cmake --build build"
        working-directory: thirdparty/ktx/source-repo
      - if: 'true'
        name: Setup cargo-json-gha-translator
        run: "mkdir -p $HOME/.local/bin && curl -o $HOME/.local/bin/cargo-json-gha-translator -L \\\n  https://github.com/Pctg-x8/cargo-json-gha-translator/releases/download/v0.1.3/cargo-json-gha-translator\nchmod +x $HOME/.local/bin/cargo-json-gha-translator"
      - if: 'true'
        name: Running Rustfmt
        run: cargo fmt -- --check
      - if: 'true'
        name: Running Clippy
        run: "set -o pipefail\ncargo clippy --all-features --all-targets --message-format=json | $HOME/.local/bin/cargo-json-gha-translator"
      - if: 'true'
        name: Running Check - Trailing Newline for Source Code Files
        run: "exec $GITHUB_WORKSPACE/.github/scripts/trailing_newline_checker.sh"
      - if: "failure()"
        uses: "actions/checkout@v5"
        with:
          ref: "${{ github.event.pull_request.head.sha }}"
      - if: "failure()"
        name: Configure for Slack Notification
        uses: "aws-actions/configure-aws-credentials@v4"
        with:
          aws-region: ap-northeast-1
          role-to-assume: arn:aws:iam::208140986057:role/GHALambdaInvoker
      - if: "failure()"
        name: Notify as Failure
        uses: "Pctg-x8/ci-notifications-post-invoker@master"
        with:
          begintime: "${{ needs.preconditions.outputs.begintime }}"
          failure_step: Code Formats
          mode: branch
          report_name: Weekly Check
          status: failure
  check-modules:
    env:
      PERIDOT_BUILD_TP_KTX_SKIP_CMAKE: '1'
      PERIDOT_BUILD_TP_SLANG_LIB_PATH: "${{ format('{0}/thirdparty/slang/source-repo/build/Release/lib', github.workspace) }}"
      PERIDOT_BUILD_TP_SLANG_SKIP_CMAKE: '1'
    name: Modules
    needs:
      - check-baselayer
      - preconditions
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - if: 'true'
        name: Disable man-db triggers for apt-get
        run: "echo \"set man-db/auto-update false\" | debconf-communicate\ndpkg-reconfigure man-db"
      - if: 'true'
        name: Checking out
        uses: "actions/checkout@v5"
        with:
          submodules: recursive
      - if: 'true'
        name: Initialize Cache
        uses: "actions/cache@v4"
        with:
          key: "${{ runner.os }}-cargo-${{ hashFiles('**/*.rs', '**/Cargo.toml') }}"
          path: "~/.cargo/registry\n~/.cargo/git\ntarget\ntools/target"
          restore-keys: "${{ runner.os }}-cargo-"
      - if: 'true'
        name: Cache ccache artifacts
        uses: "actions/cache@v4"
        with:
          key: "${{ runner.os }}-ccache-${{ hashFiles('thirdparty/slang/source-repo/**/*.c', 'thirdparty/slang/source-repo/**/*.h', 'thirdparty/slang/source-repo/**/*.cpp', 'thirdparty/slang/source-repo/**/*.hpp', 'thirdparty/slang/source-repo/**/*.inl', 'thirdparty/ktx/source-repo/**/*.c', 'thirdparty/ktx/source-repo/**/*.h', 'thirdparty/ktx/source-repo/**/*.cpp', 'thirdparty/ktx/source-repo/**/*.hpp', 'thirdparty/ktx/source-repo/**/*.inl') }}"
          path: "~/.cache/ccache"
          restore-keys: "${{ runner.os }}-ccache-"
      - if: 'true'
        name: Install ccache
        run: "sudo apt-get update && sudo apt-get install ccache"
      - if: 'true'
        name: "Pre-build c deps(slang)"
        run: "cmake --preset default -G Ninja -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_C_COMPILER_LAUNCHER=ccache -DSLANG_ENABLE_SLANG_RHI=FALSE -DSLANG_ENABLE_GFX=FALSE -DSLANG_ENABLE_SLANGD=FALSE -DSLANG_ENABLE_SLANGC=FALSE -DSLANG_ENABLE_SLANGI=FALSE -DSLANG_ENABLE_SLANGRT=FALSE -DSLANG_ENABLE_TESTS=FALSE -DSLANG_ENABLE_EXAMPLES=FALSE && cmake --build --preset releaseWithDebugInfo"
        working-directory: thirdparty/slang/source-repo
      - if: 'true'
        name: "Pre-build c deps(ktx)"
        run: "cmake . -B build -G Ninja -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_C_COMPILER_LAUNCHER=ccache -DKTX_FEATURE_TESTS=OFF -DKTX_FEATURE_VK_UPLOAD=OFF -DKTX_FEATURE_GL_UPLOAD=OFF -DKTX_FEATURE_TOOLS=OFF && cmake --build build"
        working-directory: thirdparty/ktx/source-repo
      - if: 'true'
        name: Setup cargo-json-gha-translator
        run: "mkdir -p $HOME/.local/bin && curl -o $HOME/.local/bin/cargo-json-gha-translator -L \\\n  https://github.com/Pctg-x8/cargo-json-gha-translator/releases/download/v0.1.3/cargo-json-gha-translator\nchmod +x $HOME/.local/bin/cargo-json-gha-translator"
      - if: 'true'
        name: check
        run: "exec $GITHUB_WORKSPACE/.github/scripts/checkbuild-subdir.sh"
        working-directory: modules
      - if: "failure()"
        uses: "actions/checkout@v5"
        with:
          ref: "${{ github.event.pull_request.head.sha }}"
      - if: "failure()"
        name: Configure for Slack Notification
        uses: "aws-actions/configure-aws-credentials@v4"
        with:
          aws-region: ap-northeast-1
          role-to-assume: arn:aws:iam::208140986057:role/GHALambdaInvoker
      - if: "failure()"
        name: Notify as Failure
        uses: "Pctg-x8/ci-notifications-post-invoker@master"
        with:
          begintime: "${{ needs.preconditions.outputs.begintime }}"
          failure_step: Modules
          mode: branch
          report_name: Weekly Check
          status: failure
  check-tools:
    env:
      PERIDOT_BUILD_TP_KTX_SKIP_CMAKE: '1'
      PERIDOT_BUILD_TP_SLANG_LIB_PATH: "${{ format('{0}/thirdparty/slang/source-repo/build/Release/lib', github.workspace) }}"
      PERIDOT_BUILD_TP_SLANG_SKIP_CMAKE: '1'
    name: Tools
    needs:
      - check-baselayer
      - preconditions
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - if: 'true'
        name: Disable man-db triggers for apt-get
        run: "echo \"set man-db/auto-update false\" | debconf-communicate\ndpkg-reconfigure man-db"
      - if: 'true'
        name: Checking out
        uses: "actions/checkout@v5"
        with:
          submodules: recursive
      - if: 'true'
        name: Initialize Cache
        uses: "actions/cache@v4"
        with:
          key: "${{ runner.os }}-cargo-${{ hashFiles('**/*.rs', '**/Cargo.toml') }}"
          path: "~/.cargo/registry\n~/.cargo/git\ntarget\ntools/target"
          restore-keys: "${{ runner.os }}-cargo-"
      - if: 'true'
        name: Cache ccache artifacts
        uses: "actions/cache@v4"
        with:
          key: "${{ runner.os }}-ccache-${{ hashFiles('thirdparty/slang/source-repo/**/*.c', 'thirdparty/slang/source-repo/**/*.h', 'thirdparty/slang/source-repo/**/*.cpp', 'thirdparty/slang/source-repo/**/*.hpp', 'thirdparty/slang/source-repo/**/*.inl', 'thirdparty/ktx/source-repo/**/*.c', 'thirdparty/ktx/source-repo/**/*.h', 'thirdparty/ktx/source-repo/**/*.cpp', 'thirdparty/ktx/source-repo/**/*.hpp', 'thirdparty/ktx/source-repo/**/*.inl') }}"
          path: "~/.cache/ccache"
          restore-keys: "${{ runner.os }}-ccache-"
      - if: 'true'
        name: Install ccache
        run: "sudo apt-get update && sudo apt-get install ccache"
      - if: 'true'
        name: "Pre-build c deps(slang)"
        run: "cmake --preset default -G Ninja -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_C_COMPILER_LAUNCHER=ccache -DSLANG_ENABLE_SLANG_RHI=FALSE -DSLANG_ENABLE_GFX=FALSE -DSLANG_ENABLE_SLANGD=FALSE -DSLANG_ENABLE_SLANGC=FALSE -DSLANG_ENABLE_SLANGI=FALSE -DSLANG_ENABLE_SLANGRT=FALSE -DSLANG_ENABLE_TESTS=FALSE -DSLANG_ENABLE_EXAMPLES=FALSE && cmake --build --preset releaseWithDebugInfo"
        working-directory: thirdparty/slang/source-repo
      - if: 'true'
        name: "Pre-build c deps(ktx)"
        run: "cmake . -B build -G Ninja -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_C_COMPILER_LAUNCHER=ccache -DKTX_FEATURE_TESTS=OFF -DKTX_FEATURE_VK_UPLOAD=OFF -DKTX_FEATURE_GL_UPLOAD=OFF -DKTX_FEATURE_TOOLS=OFF && cmake --build build"
        working-directory: thirdparty/ktx/source-repo
      - if: 'true'
        name: Setup cargo-json-gha-translator
        run: "mkdir -p $HOME/.local/bin && curl -o $HOME/.local/bin/cargo-json-gha-translator -L \\\n  https://github.com/Pctg-x8/cargo-json-gha-translator/releases/download/v0.1.3/cargo-json-gha-translator\nchmod +x $HOME/.local/bin/cargo-json-gha-translator"
      - if: 'true'
        name: check
        run: "exec $GITHUB_WORKSPACE/.github/scripts/checkbuild-subdir.sh"
        working-directory: tools
      - if: "failure()"
        uses: "actions/checkout@v5"
        with:
          ref: "${{ github.event.pull_request.head.sha }}"
      - if: "failure()"
        name: Configure for Slack Notification
        uses: "aws-actions/configure-aws-credentials@v4"
        with:
          aws-region: ap-northeast-1
          role-to-assume: arn:aws:iam::208140986057:role/GHALambdaInvoker
      - if: "failure()"
        name: Notify as Failure
        uses: "Pctg-x8/ci-notifications-post-invoker@master"
        with:
          begintime: "${{ needs.preconditions.outputs.begintime }}"
          failure_step: Tools
          mode: branch
          report_name: Weekly Check
          status: failure
  preconditions:
    name: Preconditions
    outputs:
      begintime: "${{ steps.begintime.outputs.begintime }}"
    runs-on: ubuntu-latest
    steps:
      - name: Disable man-db triggers for apt-get
        run: "echo \"set man-db/auto-update false\" | debconf-communicate\ndpkg-reconfigure man-db"
      - id: begintime
        name: Getting begintime
        run: "echo \"begintime=$(date +%s)\" >> $GITHUB_OUTPUT"
      - name: Checking out
        uses: "actions/checkout@v5"
        with:
          submodules: recursive
      - name: Cache ccache artifacts
        uses: "actions/cache@v4"
        with:
          key: "${{ runner.os }}-ccache-${{ hashFiles('thirdparty/slang/source-repo/**/*.c', 'thirdparty/slang/source-repo/**/*.h', 'thirdparty/slang/source-repo/**/*.cpp', 'thirdparty/slang/source-repo/**/*.hpp', 'thirdparty/slang/source-repo/**/*.inl', 'thirdparty/ktx/source-repo/**/*.c', 'thirdparty/ktx/source-repo/**/*.h', 'thirdparty/ktx/source-repo/**/*.cpp', 'thirdparty/ktx/source-repo/**/*.hpp', 'thirdparty/ktx/source-repo/**/*.inl') }}"
          path: "~/.cache/ccache"
          restore-keys: "${{ runner.os }}-ccache-"
      - name: Install ccache
        run: "sudo apt-get update && sudo apt-get install ccache"
      - name: "Pre-build c deps(slang)"
        run: "cmake --preset default -G Ninja -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_C_COMPILER_LAUNCHER=ccache -DSLANG_ENABLE_SLANG_RHI=FALSE -DSLANG_ENABLE_GFX=FALSE -DSLANG_ENABLE_SLANGD=FALSE -DSLANG_ENABLE_SLANGC=FALSE -DSLANG_ENABLE_SLANGI=FALSE -DSLANG_ENABLE_SLANGRT=FALSE -DSLANG_ENABLE_TESTS=FALSE -DSLANG_ENABLE_EXAMPLES=FALSE && cmake --build --preset releaseWithDebugInfo"
        working-directory: thirdparty/slang/source-repo
      - name: "Pre-build c deps(ktx)"
        run: "cmake . -B build -G Ninja -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_C_COMPILER_LAUNCHER=ccache -DKTX_FEATURE_TESTS=OFF -DKTX_FEATURE_VK_UPLOAD=OFF -DKTX_FEATURE_GL_UPLOAD=OFF -DKTX_FEATURE_TOOLS=OFF && cmake --build build"
        working-directory: thirdparty/ktx/source-repo
  report-success:
    name: Report as Success
    needs:
      - check-baselayer
      - check-cradle-android
      - check-cradle-linux
      - check-cradle-macos
      - check-cradle-windows
      - check-examples
      - check-formats
      - check-modules
      - check-tools
      - preconditions
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checking out
        uses: "actions/checkout@v5"
        with:
          submodules: recursive
      - name: "Checking out (HEAD commit)"
        uses: "actions/checkout@v5"
        with:
          ref: "${{ github.event.pull_request.head.sha }}"
          submodules: recursive
      - uses: "actions/checkout@v5"
        with:
          ref: "${{ github.event.pull_request.head.sha }}"
      - name: Configure for Slack Notification
        uses: "aws-actions/configure-aws-credentials@v4"
        with:
          aws-region: ap-northeast-1
          role-to-assume: arn:aws:iam::208140986057:role/GHALambdaInvoker
      - name: Notify as Success
        uses: "Pctg-x8/ci-notifications-post-invoker@master"
        with:
          begintime: "${{ needs.preconditions.outputs.begintime }}"
          mode: branch
          report_name: Weekly Check
          status: success
name: "Integrity Check (Weekly)"
on:
  schedule:
    - cron: "0 12 * * wed"
